hackclub/dns

hackclub.com.yaml
=> Point schacks.hackclub.com to schacks.netlify.com

hackchicago.io.yaml
Duplicate of #24. Needed to make this dupe because CircleCI refuses to run tests for people who aren't collaborators on the repo to prevent exposure of API keys.
I've since added @hackclub/staff as collaborators to this repo, so shouldn't run into this in the future for core.
=> Add Mailchimp

hackchicago.io.yaml
=> Add DMARC for MailChimp

hackchicago.io.yaml
=> Remove DMARC

hackchicago.io.yaml
(The tests don't run on PRs, only branches)
=> Replacement PR for #36

hackclub.com.yaml
Trying an ALIAS first because I think CNAME can cause issues with SSL certs (I think)
=> Add ALIAS record for new.hackclub.com

hackclub.com.yaml
**Do NOT merge until the following conflict is resolved!!!** 
Nginx config is scary. I do not want to touch it >w<
=> Add Hack Club Leadership Guide

hackclub.com.yaml
=> New minecraft server + entry for host

hackclub.com.yaml
=> Add RAHS Hack Club

hackclub.com.yaml
=> Added Alpharetta Hack Club

hackclub.com.yaml
=> Add p2p Hack Club DNS

hackclub.com.yaml
=> Update to Netlify CNAME

hackclub.com.yaml
Added new DNS records for dedicated.servers.hackclub.com and mc.hackclub.com
=> Update HackClub dedicated server

hackclub.com.yaml
Added SMHS hack club subdomain
=> Update smhs.hackclub.com in hackclub.com.yaml

hackclub.com.yaml
Adding Stripe records for Bank
=> Update to send Stripe Invoices from billing@hackclub.com

hackclub.com.yaml
=> Add api2.hackclub.com

hackclub.com.yaml
=> Re-add vmc.hackclub.com

hackclub.com.yaml
Closes https://github.com/hackclub/dns/pull/221
=> Add packages.hackclub.com

hackclub.com.yaml
=> Revert "temporarily remove shop A record while fixing circleci"

hackclub.com.yaml
I'll merge this when it's ready
=> Add markdown.hackclub.com

hackclub.com.yaml
https://github.com/hackclub/site/pull/611
=> Switch site to Now

hackclub.com.yaml
Moves to different VM from unique container
=> Update mumble IP

hackclub.com.yaml, hackclub.io.yaml
=> Add Hack University!

hackclub.com.yaml
Changing the redirect; it's been outdated for a while now.
=> Update TitanHacks DNS

hackclub.com.yaml
=> Add Subdomain for Summer of Making

hackclub.com.yaml
=> pexip stuff

hackclub.com.yaml
So Zeit/Vercel likes to do stuff differently, so i just used netlify
=> Add Summer of Making (Attempt 2)

hackclub.com.yaml
Setting up a development server for Max and myself
=> Add zapdos.servers.hackclub.com

hackclub.com.yaml
=> Added Is the video done

hackclub.com.yaml
```
- ttl: 3600
type: TXT
value: v=spf1 include:_spf.google.com ~all
- ttl: 3600
type: MX
values:
- exchange: aspmx.l.google.com.
preference: 1
- exchange: alt1.aspmx.l.google.com.
preference: 5
- exchange: alt2.aspmx.l.google.com.
preference: 5
- exchange: alt3.aspmx.l.google.com.
preference: 10
- exchange: alt4.aspmx.l.google.com.
preference: 10
```
=> Remove all records other than A record

hackclub.com.yaml
keeping the site alive but confirming the a record is the issue
=> Go fully back to using the CNAME record

hackclub.com.yaml
=> Add restrictions for slack bots

hackclub.com.yaml
unfortunately, the api doesn't seem like repl.it very much. It works on @lukec11's server though perfectly.
=> Update slack restriction URL

hackclub.com.yaml
I hope this works lol. if it doesn't blame @lukec11 he checked it for me.
=> add shop.hackclub.com g suite

hackclub.com.yaml
=> Add summer DNS records

hackclub.com.yaml
=> Revert "Add summer DNS records"

hackclub.com.yaml
Updating this so that the site utilizes HTTPS (due to now incorporating user input)
=> Update isthevideodone.hackclub.com to proper CNAME

hackclub.com.yaml
Reverts hackclub/dns#320 b/c the test & build succeeded
=> Revert "Test GitHub Actions"

hackclub.com.yaml
Check out https://github.com/hackclub/hack-coins to know more!
=> hack coins domain!

hackclub.com.yaml
Updated India record so that hack club-india's new website can be hosted.
=> update India Record

hackclub.com.yaml
Hi! Hoping you could add the webring to Hack Club. Thanks!
=> Add the Hack Club Webring!

hackclub.com.yaml
Add blog subdomain to our @ctrl-alt-tec domain :)
=> Add blog.ctrl-alt-tec.hackclub.com

hackclub.com.yaml
Need a subdomain for our club because of using netlify.app seems unprofessional.
=> Add singgasana.hackclub.com

hackclub.com.yaml
Direct ctf.hackclub.com to the website created by @sampoder
=> Add ctf.hackclub.com

hackclub.com.yaml
Moving personal projects to dedicated cluster to save costs, incl. is the video done.
=> Update isthevideodone.hackclub.com to resolve to new K8 cluster

hackclub.com.yaml
=> Add leap.hackclub.com

hackclub.com.yaml
=> Revert "Added Front SPF/DKIM"

hackclub.com.yaml
=> Re-implement "Added Front SPF/DKIM"

hackclub.com.yaml
=> add tist.hackclub.com domain

hackclub.com.yaml
for my little project of today: https://leap-manual.vercel.app/
also what's the current status of dns, is it working?
=> add leap manual to dns

hackclub.com.yaml
Add endpoint for [https://ctrl-alt-tec.herokuapp.com](https://ctrl-alt-tec.herokuapp.com)
=> Add api.ctrl-alt-tec.hackclub.com

README.md
Signed-off-by: Matthew Gleich <email@mattglei.ch>
=> 📝 Detail how to add a subdomain

hackclub.com.yaml
I call dibs on signing up :p
This fixes #387, fixes #393, and fixes https://github.com/hackclub/orpheushacks/issues/3.
=> Add orpheushacks to DNS

hackclub.com.yaml
Set a CNAME record: gaynormccown.netlify.app. for subdomain: gaynormccown.hackclub.com
=> Updated GaynorMcCown.HackClub.com DNS records.

hackclub.com.yaml
Create a CNAME record from catlin.hackclub.com that points to cgmsp.kazmal.tech.
=> add catlin hackclub website

hackclub.com.yaml
=> Revert "Added shop.gaynormccown.hackclub.com"

hackclub.com.yaml
=> Revert "Bring back TXT spf for gaynormccown.hackclub.com"

hackclub.com.yaml
Replaced ImprovMX with Google Workspace Records for GaynorMcCown.HackClub.com
=> Verify gaynormccown.hackclub.com Google Workspace

hackclub.com.yaml
Change domain that catlin.hackclub.com points to to catlin.netlify.app from cgmsp.kazmal.tech. See #415.
=> Update my CNAME record for catlin.hackclub.com.

hackclub.com.yaml
Hi. Can you add `warsaw.hackclub.com` for Hack Club Warsaw (prev. Palace of Youth)? :smile:
=> Add warsaw.hackclub.com

hackclub.com.yaml
Hopefully makes `clphscec.web.app` accessible through `cec.hackclub.com`
=> Add CEC subdomain

hackclub.com.yaml
=> Google Workspace for flhs-hacks.hackclub.com on Hack Club Bank

hackclub.com.yaml
This is our first time connecting a custom domain with Firebase Hosting, and I forgot to add a TXT record for it 😅
Hope things go well 👍
=> Add TXT record for CEC

hack.af.yaml
This hooks e.hack.af up to the event hn giveaway thing, so `http://e.hack.af/<code>` gets you free moolah 💸
(cc @rishiosaur, @zachlatta, and @zfogg)
=> Add e.hack.af

hackclub.com.yaml
https://bank.hackclub.com/g_suites/632
=> Change FHLS's HCB Google Workspace domain

hackclub.com.yaml
Hello PR team, I am almost done creating my website, I think, I should put it online as I am finishing up. 
You can review the website, which is for the hack club south Africa, and I am the leader for the club.
If you have any thought about the website Pls let me know.
thanks
=> added a subdomain for my club

hackclub.com.yaml
=> Add Asia Summit / Conf Domains

hackclub.com.yaml
=> Fix sshchat.hackclub.com

hackclub.com.yaml
I renamed my project to devzat so I was hoping I could update this too :)
Thanks,
Ishan
=> Change sshchat to devzat

hackclub.com.yaml
added 
modded-mc.hackclub.com for the modded mc server
beta-mc.hackclub.com for the experimental mc server(not always used)
=> Added srv records for minecraft server

hackclub.com.yaml
Hey, this isn't urgent but we switched hosting from netlify to cloudflare pages.
=> switch hosting from netlify to cloudflare pages

hackclub.com.yaml
=> Update Devzat IP to 150.136.142.44

hackclub.com.yaml
Just in case people use the old domain
=> Change sshchat to 150.136.142.44 as well

hackclub.com.yaml
Added conant.hackclub.com for the Conant High School Hack Club website :)
=> Added conant.hackclub.com for the Conant High School Hack Club website

hackclub.com.yaml
- Added the Firebase Value for the sub-domain.
=> Updated the ITER Sub Domain with Firebase Value.

hackclub.com.yaml
https://github.com/garyhtou/bank-bloggers
=> Add `bank-bloggers` subdomain for Bank use case demo

hackclub.com.yaml
Added the DNS settings to make coet.hackclub.com domain name available
=> hackclub coet website dns added

hackclub.com.yaml
this is a domain for the Hackinux challenge that HC APAC is organizing.
=> chore: add hackinux domain for hc apac challenge

hackclub.com.yaml
Add domain for Ronald Reagan High School's club website.
=> Add Domain for Ronald Reagan HS

hackclub.com.yaml
=> Add the Podcast Site

hackclub.com.yaml
=> Add DVHackClub Domain

hackclub.com.yaml
the following sub-domain was requested by a club in APAC, this pull request adds it to the DNS.
The sub-domain requested is = bulc.hackclub.com
=> add ( subdomain ): add sub-domain bulc for a Hack Club in APAC

hackclub.com.yaml
Adding my club's Hack Club website to the list.
=> Add Park Lane International School Hack Club

hackclub.com.yaml
Added the subdomain for Hack the October Subdomain.
=> [add] : Hack the October Subdomain

hackclub.com.yaml
This is for a website I'm making for my school's hack club.
=> Add rhs subdomain

hackclub.com.yaml
Add DNS for tilde.hackclub.com
=>  Add tilde.hackclub.com

hackclub.com.yaml
The old GitHub site wasn't working so I changed the site to netlify.
=> Updated website from Github to Netlify

hackclub.com.yaml
Add the EPS Hack Club website
contacts if there's a problem:
eoreizy@eastsideprep.org
rjhangiani@eastsideprep.org
=> Add "Hack Club EPS" subdomain (eps.hackclub.com)

hackclub.com.yaml
=> Please add amity subdomain (amity.hackclub.com)

hackclub.com.yaml
add MX, SPF, and A records for `oly.hackclub.com`
=> add oly.hackclub.com

hackclub.com.yaml
Add MX record for mail exchange
=> Add MX record to tilde.hackclub.com

hackclub.com.yaml
Website is a letter to a donor with some private information within so it's not open sourced.
=> add domain for donor site

hackclub.com.yaml
Website is a letter to a donor with some private information within so it's not open sourced.
=> add domain for donor site 

hackclub.com.yaml
=> making a test wordpress site

dino.icu.yaml
adding dino.icu for the community to use!
=> add dino.icu

config/production.yaml, dino.icu.yaml
oops I missed adding the domain to the `production.yaml` file
=> add dino.icu to production.yaml

dino.icu.yaml
=> Create stickers subdomain for discord-stickers.netlify.app

dino.icu.yaml, hackclub.com.yaml
=> Created kevin subdomain for dino.icu

dino.icu.yaml
=> Create low-ping.dino.icu for  lem6ns/rbx-low-ping-finder

dino.icu.yaml
=> += scales.dino.icu

hackclub.com.yaml
=> had to update because the website wasnt working

hackclub.com.yaml
Updated nust.hackclub.com to netlify website.
=> 📦 NEW: updated nust.hackclub.com

dino.icu.yaml
=> Add <https://pay.dino.icu>

dino.icu.yaml
yes
https://github.com/niilasoika/niilas.dino.icu
=> add niilas.dino.icu

hackclub.com.yaml
Subdomain for tracking sticker shipments we send within India
=> Adding tracking.hackclub.com

hackclub.com.yaml
Please add a subdomain for Hack Club Austin!
=> Add austin.hackclub.com

hackclub.com.yaml
=> remove saimaa.hackclub.com

hackclub.com.yaml
so i can manage them automagically with caddy or certbot
=> moving some of these to dnsimple zones

hackclub.com.yaml
=> Zfogg tilde zephyrnet dnsimple

.gitattributes
It'll look something like this:
=> Mark YAML files as Linguist-detectable

hackclub.com.yaml
The previous source domain was not able to connect with the subdomain. Please update this file.
=> Updating Source Domain

hackclub.com.yaml
=> Revert "Updating Source Domain"

dino.icu.yaml
Add a hack club dinosaur api to geta.dino.icu
=> Add geta.dino.icu

hackclub.com.yaml
=> Update Hackclub.com.yml File

hackclub.com.yaml
We have created a new website for our club so wanted the existing entry to the redirect to new domain name
=> updated the value

hackclub.com.yaml
=> HackClub CGC

dinosaurbbq.org.yaml
I changed my GitHub username. :cloud-thoughts-head-empty:
=> Update CNAME for wwww

hackclub.com.yaml
=> Add straya.hackclub.com

dino.icu.yaml
yes, the actual name of the project is "e" (絵).
the repo has only been in existence for about 20 minutes, so it's almost empty, but i wanted to get the DNS stuff dealt with early; i have an MVP elsewhere.
=> add dino.icu e record

hackclub.com.yaml
=> adding thorn.hackclub.com -> our website!

hackclub.com.yaml
- Adds Hackerabad homepage to the Hack Club DNS, deployed over Netlify
=> Added Hackerabad

hackclub.com.yaml
So we can link to it from GitHub :)
=> Add css-starter

dino.icu.yaml
Adds icons.dino.icu going to https://icons-dino-icu.vercel.app
Tiny project to act as a CDN for @hackclub/icons
`https://icons-dino-icu.vercel.app/api/icons/colors/red/glyphs/download.svg`
=> add icons.dino.icu

hackclub.com.yaml
Related to https://github.com/hackclub/toriel/pull/1
=> Add toriel bot server

hackclub.com.yaml
Add zguide.hackclub.com -> yodalightsabr.github.io/slashz-guide.
=> Add slash-z guide

dino.icu.yaml
Add emojile.dino.icu > yodalightsabr.github.io.
You can preview emojile [here](https://workshop-starter-wordle.yodacode.repl.co/)
=> Add emojile.dino.icu

config/production.yaml, wackclub.com.yaml
=> Add wackclub.com

README.md
Vercel now allows using domains across multiple accounts :D
=> Remove vercel limitation

hackclub.com.yaml
Now that Vercel supports subdomains, I have added the TXT record as per the documentation.
=> Added Hackerabad Vercel TXT Record

hackclub.com.yaml
This typo is seems to be blocking new PR
=> fixed a typo in the previous PR

hackclub.com.yaml
https://github.com/hackclub/bank-shields
=> Bank Shields

hackclub.com.yaml
moved include to the other includes
=> Attempt to fix mailgun

hackclub.com.yaml
=> dino explorer 

hackclub.com.yaml
For testing changes to Assemble ticketing without disrupting production
=> ticketing dev branch

hackclub.com.yaml
Let's add a contributing file, so we can work better, together!
=> stemegypt.hackclub.com

hackclub.com.yaml
Can someone check if I did the vercel verification correctly? Thanks!
=> Update blair.hackclub.com, add vercel verification

hackclub.com.yaml
(Not yet configured in Vercel, but I can do that if it'd be helpful)
=> Add sprig.hackclub.com

bank.engineering.yaml
Hello!
I made a project for Bank: Hack Club BancURL. It fetches from the transparency API the latest balance & transaction data and displays them when you cURL the server!  I was wondering if I could ship it on https://curl.bank.engineering. I doubt it - but I thought it was worth a shot.
You can try it by running `curl https://hcb.deno.dev/${orgname}`
Screenshot:
=> Add curl.bank.engineering

hackclub.com.yaml
=> Revert "stemegypt.hackclub.com"

hackclub.com.yaml
so sorry for all the prs!! 😬 but this is to verify for vercel
=> Verify domains under _vercel

hackclub.com.yaml
so sorry for all the prs!! 😬(x2) but this is for vercel
=> Add cname vercel records - puyallup/phs

hackclub.com.yaml
Added forms.phs.hackclub.com as well as vercel verification.
=> Add forms.phs.hackclub.com

hackclub.com.yaml
Removed: hacktheoctober.netlify.app
Added: hacktheoctober.vercel.app
=> Added vercel domain verification for hacktheoctober

hackclub.com.yaml
I lead a hackclub at the North Carolina School of Science and Mathematics (NCSSM). Here's the website we want to deploy onto `ncssm.hackclub.com`: https://ncssm-hackclub-site.vercel.app/
=> Add `ncssm.hackclub.com`

hackclub.com.yaml
Hey, this is Thomas from the Dorman Hack Club. I am connecting the Dorman.HackClub.com domain to our club's website.
=> Dorman Hack Club domain added

config/production.yaml
see discussion in #zrl-land (https://hackclub.slack.com/archives/C01FXNNF6F2/p1665055415107649)
=> Remove alphabetical requirement

hackclub.com.yaml
Hello! I would like to try to add the SMCHS Hack Club website to the dns.
=> Added the SMCHS Hack Club website to the DNS

hackclub.com.yaml
=> Update gitpage link.

hackclub.com.yaml
=> Revert "Update gitpage link."

hackclub.com.yaml
@meashna please refer to recent pull requests by others.
remove the pull request as this is an emergency.
=> added hackaway

hackclub.com.yaml
Added teenhack.hackclub.com to redirect to teenhackse.org (hackathon website)
=> Added teenhack subdomain

hackclub.com.yaml
Added Vercel verification records for GaynorMcCown.HackClub.com (My Hack Club's website) & Saleh.hackclub.com (My Hack Clubber Page, part of Hack Club Webring).
=> Gaynor McCown Hack Club Vercel Verification

hackclub.com.yaml
Adds a Google Workspace verification record
=> Epoch BA Google Workspace records

hackclub.com.yaml
=> Epoch BA Fix

hackclub.com.yaml
=> Epoch Fix #2

hackclub.com.yaml
Added lghs.hackclub.com for the Locust Grove High Hack Club website :D
=> Add `lghs.hackclub.com` for Locust Grove High

hackclub.com.yaml
Add a few subdomains after today's HC club meeting
=> Add a few subdomains to cchs.hackclub.com

hackclub.com.yaml
Bank wrapped is a work in progress, but I need to get the domain working so I can link it to bank.
=> Add bank wrapped

hackclub.com.yaml
Hey, 
I'm requesting a dns for a website I built for epoch on its theme.
=> DNS request for EPOCH project

dino.icu.yaml
=> add diafano.dino.icu

dino.icu.yaml
code open source at:
https://github.com/ZeroQLi/winterlings
=> addition of subdomain for winterlings site

dino.icu.yaml
https://channels.dino.icu -> https://slack-channels.vercel.app/
=> Add channels.dino.icu

hackclub.com.yaml
Added _minecraft SRV and updated the mc cname to hebra.365hosts.network
=> Add new minecraft server

hackclub.com.yaml
I think this broke the build for all srv records, see last build log
Untested
=> fix most recent change

hackclub.com.yaml
=> Add my subdomain

hackclub.com.yaml
=> ASIET Webpage

hackclub.com.yaml
=> Revert "Add CodetheTech Domain"

hackclub.com.yaml
add vps as 1 record
add future srv records
=> prepare for minecraft server migration

hackclub.com.yaml
supersedes #857 
requires #858 
switches over dns to point to new server
=> perform minecraft server migration

hackclub.com.yaml
Beware!  This is my first PR in this repo so I'd appreciate a double-check.  The goal is to add a new subdomain, sinerider-scoring.hackclub.com.
=> add sinerider-scoring.hackclub.com

hackclub.com.yaml
This PR is to add a subdomain for my club.
=> Added New Canaan

hackclub.com.yaml
=> DNS Verification for new Checkly dashboard

hackclub.com.yaml
As soon as a vercel project is up for Angelhacks YYZ, this should work
=> add angelhacks-yyz domain

hackclub.com.yaml
Well hellow there,
I'm trying to get this subdomain verified with vercel so that I can host my beaaaautiful club website !
=> Added codecafe.hackclub.com !

dino.icu.yaml
=> Change dino.icu.yaml

hackclub.com.yaml
Testing for https://github.com/hackclub/dns/pull/901
=> Setting up CNAME for testing Bank's DNS on ALIAS

hackclub.com.yaml
Testing for https://github.com/hackclub/dns/pull/901
=> Change `bankalias` from CNAME to ALIAS

hackclub.com.yaml
Reverts hackclub/dns#903
It failed to deploy
=> Revert "Change `bankalias` from CNAME to ALIAS"

hackclub.com.yaml
Coreferencing https://github.com/hackclub/global/pull/79
=> Add japan global site DNS record

hackclub.com.yaml
https://github.com/hackclub/global/pull/85
=> Add te.hackclub.com

hackclub.com.yaml
This PR is to add a subdomain for my club that was just approved.
=> Added New Canaan Library

hackclub.com.yaml
Sorry about the mess up last time, this is my first time doing this!
=> _vercel in alphabetical order. MHS hackclub

hackclub.com.yaml
=> Update `status.hackclub.com` to  new Checkly CNAME

hackclub.com.yaml
This is putting the website [ihshack.vercel.com](https://ihshack.vercel.app/) as a subdomain of hackclub.com
=> Add ihs.hackclub.com as a subdomain

hackclub.com.yaml
The previous pull request I created had the wrong CNAME with vercel. I checked their docs again and now have the right CNAME in the .yaml file.
=> Update CNAME settings for ihs.hackclub.com

hackclub.com.yaml
=> Add irvine.hackclub.com

hackclub.com.yaml
Add Google Workspace for irvine.hackclub.com -> ihs-hack-club on HCB
=> Add Google Workspace for irvine.hackclub.com -> ihs-hack-club on HCB

hackclub.app.yaml
- Add secure.vm subdomain
- CNAME ts.hackclub.app to secure.vm subdomain
- Update ip addresses of @ and * record to new primary vm
=> Nest stuff

hackclub.com.yaml
This is for the Hack Club Naval Armada Flag Referendum
=> Add flagvote subdomain

dino.icu.yaml
=> Add click.dino.icu

hackclub.com.yaml
https://github.com/hackclub/global 
used for this translation project (work in progress)
=> added de subdomain for translated webiste

hackclub.com.yaml
I updated the DNS record for lasa.hackclub.com
=> Change LASA Hack Club website

hackclub.com.yaml
in an attempt to unblock the dns pr queue
=> remove lasa entry

hackclub.com.yaml
This record was only needed for setting up the feature
=> Remove 1pass verification

.github/workflows/validate.yml
=> added github action to validate yaml files

hackclub.com.yaml
=> new url for my website

hackclub.app.yaml
Reverts hackclub/dns#999
This is a temporary rollback while trying to fix the deployment. Sorry @reesericci!
=> Revert "Delegate to nest DNS"

hackclub.com.yaml
Reverts hackclub/dns#1008 / re-adds https://github.com/hackclub/dns/pull/996
=> Bring back Boston Latin School (BLS HACK)

dino.icu.yaml
=> Add skyfall.dino.icu

hackclub.com.yaml
These have already been removed on SendGrid
=> Remove unused HCB sendgrid domains

hackclub.com.yaml
=> Can I have a subdomain of hackclub.com for NTP Hack Club?

hackclub.com.yaml
We want northpark.hackclub.com to point to our club's website, nphack.club
=> Add northpark.hackclub.com

.github/CODEOWNERS
Add dns-friends as a codeowner of whole repo
=> Add dns-friends

hackclub.com.yaml
=> Redirect jam.hackclub to jams.hackclub

hackclub.org.yaml
Re: https://github.com/hackclub/dns/pull/1061
=> Set up Instantly.ai custom tracking proxy

hackclub.com.yaml
Boston Day of Service (Think Like a Programmer) website domain added
=> Added tlap.hackclub.com

hackclub.com.yaml
We are from #the-summit! See you soon :)
=> Add Orpheus Odyessy

hackclub.com.yaml
👋🏼 @devenjadhav is going to merge this.
📢 Excited to push my #the-summit project to prod!🥳
=> Adding orpheusodyssey to the DNS

dino.icu.yaml
Using dino.icu subdomain for personal website!
=> Add `vansh.dino.icu`

config/production.yaml, hack.club.yaml
This should make hack.club point to the same thing as hack.af
=> Adding hack.club - or at least attempting to

dino.icu.yaml
Adding DNS for personal website.
=> Add `piyush.dino.icu`

hackclub.app.yaml
We stopped having mailboxes on mail.hackclub.app
=> Remove `mail.hackclub.app` MX, DKIM, and DMARC records

hackclub.app.yaml
This PR adds the ACME challenge txt for `hackclub.app`
=> Add `_acme-challenge.hackclub.app`

hackclub.app.yaml
After some testing it has been decided that this is no longer needed
=> Remove `_acme-challenge.hackclub.app`

hackclub.com.yaml
Hey, vice president of the stemegypt branch for the 2024 season here! I updated the stemegypt subdomain to the new CNAME records.
=> Update the stemegypt.hackclub.com CNAME records

hackclub.app.yaml
=> Add AAAA (IPv6) records to `hackclub.app`

hackclub.com.yaml
=> Add `asmgame.hackclub.com`

hackclub.com.yaml
This updates the TTL from 1 to 3600 after I mistakenly approved the PR before noticing the error in #1111
=> Updating TTL on `status.hcb.hackclub.com`

dino.icu.yaml
Add write.dino.icu, WriteFreely instance.
=> Adding write.dino.icu

hackclub.com.yaml
=> Add `.hackclub.com`

dino.icu.yaml
This subdomain will be used to point to my new project, Spend Hack Club HQ's Money! It is hosted on Vercel.
=> Adding spend.dino.icu

hackclub.com.yaml
=> Add Apocalypse

hackclub.com.yaml
added TXT record for GitHub pages challenge
=> Adding `_github-pages-challenge-cghs-hackclub.cghs.hackclub.com`

hackclub.com.yaml
codeabit is a hack club started recently in Kuwait by me (@husseinamine) A high school student. the first of its kind here, In hopes to open up a lot of new people to coding and electronics
=> Adding codeabit.hackclub.com

hackclub.com.yaml
kr to ko according to ISO 639-1 of Korean
=> Add `ko.hackclub.com`

hackclub.app.yaml
This PR adds SSHFP records for `hackclub.app` so it can be checked by SSH clients to ensure they are connecting to the proper host.
=> Updating `hackclub.app` - add SSHFP records

hackclub.app.yaml
This PR updates the SSHFP fingerprints for `hackclub.app`
=> Updating `hackclub.app` SSHFP fingerprints

hackclub.app.yaml
Fix the Nest SSHFP records with the really correct values.
=> Fix the Nest SSHFP records

hackclub.com.yaml
Updated dns target for `wl.hackclub.com`.
=> Updating `wl.hackclub.com`

hackclub.com.yaml
=> dns verification for evergreen 

dino.icu.yaml, hackclub.com.yaml
The subdomain node.dino.icu will be used by me for my personal website
=> Adding node.dino.icu

hackclub.com.yaml
PR for adding db.hackclub.com. The subdomain will be used by Don Bosco Technical Institute of Makati for their Hack Club website.
=> db.hackclub.com

.github/workflows/test.yml
Update checkout & python action dependencies
=> Update deps for CI test

hackclub.com.yaml
=> Updating ham.hackclub.com

.github/workflows/deploy.yml
Update checkout & python action dependencies
=> Update deps for deploy action

dino.icu.yaml
Work on my cool dino.icu mini site that I designed in Figma but haven't created yet
=> Claim yc.dino.icu.

bin/sync
Will be reverted after 1 time run
=> Temp Run dns with  --force to resolve TTL bulk update

bin/sync
=> Removes temporary --force

dino.icu.yaml
this will be my padfolio website i am slowly building it for now i have a poem written on it i plan to add my socials and show case my projects in future
=> Adding terror.dino.icu

hackclub.com.yaml
Adding subdomain for Jagiellon BitBrewers website. It will be used for posting projects and encouraging people to join our hackclub.
=> Adding `jagiellonbitbrewers.hackclub.com`

dino.icu.yaml
print.dino.icu → https://print-chi.vercel.app
=> print.dino.icu

hackclub.com.yaml
=> Adding nairobi.hackclub.com

hackclub.com.yaml
Using DNS records from HCB page
=> hcarc.hackclub.com: Update MX to google workspace

hackclub.com.yaml
=> Updating alopb.hackclub.com

hackclub.com.yaml
Website subdomain for new you ship we ship:
https://cider.hackclub.com
=> Add cider subdomain

dino.icu.yaml
`jzaleta.dino.icu` → My personal twitter profile (_while I finish building my website_) https://x.com/_jzaleta
=> Adding jzaleta.dino.icu

dino.icu.yaml
Change to point for my homelab to use reverse proxy to the site, since neocities won't disable ssl from this Slack Message :
https://hackclub.slack.com/archives/C06KMENGHQC/p1716588335739969
=> Update toonnongaeoy.dino.icu to my homelab.

hackclub.com.yaml
I'm adding the riverside subdomain
=> Added riverside subdomain

hackclub.com.yaml
This adds hackhour as a subdomain so we can provide the API for the hack hour clock https://github.com/hackclub/hack-hour/pull/24/files
=> Add hackhour subdomain

hackclub.com.yaml
=> Add fraps.hackclub.com to hackclub.com.yaml

hackclub.com.yaml
=> Remove TXT fraps record hackclub.com.yaml

hackclub.com.yaml
=> Revert Arcadius ngrok link

dino.icu.yaml, hackclub.com.yaml
=> hcarc.hackclub.com: Add Vercel CNAME

hackclub.com.yaml
It's the bot for #library and the subdomain keeps changing with Heroku + I would like to have it display a page to users
=> Addding librarian.hackclub.com

hackclub.com.yaml
Building a chatlog so that people staying at UVM can check where others are. Basically those whiteboards you put up in front of your door in college dorms, but jank and digital. Called heist because it sounds cool.
=> Adding heist.hackclub.com

dino.icu.yaml
You can preview my handmade dino page [here](https://dino-icu.pages.dev).
=> Adding pc.dino.icu, mcpepc.dino.icu, jaehyeon.dino.icu, mcpe-pc.dino.icu

hack.club.yaml
This will add l.hack.club for URL shortening of Librarian at the request of @polytroper
=> Add librarian to hack.club for URL shortning

hackclub.com.yaml
The ten days of code website will be used to promote the program the next time it runs and to document it's first run during summer '24.
=> Adding `ten-days-of-code.hackclub.com`

hackclub.com.yaml
Adding the subdomain for the new version of Days of Service
=> added athena.hackclub.com

hackclub.com.yaml
I will be using the subdomain as my main personal website.
=> Adding arson.dino.icu

hackclub.com.yaml
=> Added Vercel verification for forge.hackclub.com

hackclub.com.yaml
=> Revert "Adding arson.dino.icu"

dino.icu.yaml, hackclub.com.yaml
This will be used as my personal website. I intended for dino.icu to be the domain but accidentally added my request to hackclub.com.yaml first :/ (oops)
=> adding 'arson.dino.icu'

bank.engineering.yaml
docs for https://github.com/hackclub/yellow_pages
=> Add `yellowpages.bank.engineering` (on Vercel)

dino.icu.yaml
Hi, it's me Vic. This is a pr trying to add a CNAME to sk.dino.icu pointing to my hackclub nest subdomain. It's intended to be used for a unofficial sharkey (misskey fork) hackclub instance, I have the docker ready but I cant show anything neither start it rn bcuz activity pub don't allow to change domains (for federation). But it will be a sharkey instance with hackclub branding. :)
=> Adding sk.dino.icu

hackclub.com.yaml
Updated the hackclub.com.yaml for our days of service event called Luna.
=> Adding luna.hackclub.com

dino.icu.yaml
So now the Sharkey instance name is Hackey so I want to move the domain to hk.dino.icu so its more software agnostic and if we want to change the software it would be easier, thanks 😓 sorry for making a pr again
=> Add hk.dino.icu

dino.icu.yaml, hackclub.com.yaml
codingcrew.dino.icu will be used as a website for my coding community / hack club I am setting up in my city in the UK. It outlines what the community will do and how to sign up!
=> Adding codingcrew.dino.icu

dino.icu.yaml
I am adding a subdomain for my personal website. The website is a portfolio for all the projects I make.
=> Adding amina.dino.icu

hackclub.com.yaml
Adding a domain for Lambert High School's Hack Club website. Points to -> https://lambert-hackclub.vercel.app/
=> Adding lambert.hackclub.com

dino.icu.yaml
I'm moving it to saishack.club/brig. soon™
=> Remove old domain for new project

hackclub.com.yaml
Recreating an events page for SAD and HC events at large!
=> Add eventmasterapi.hackclub.com

hackclub.com.yaml
for email deliverability!
DKIM: https://github.com/hackclub/dns/pull/1064
SPF: https://github.com/hackclub/dns/pull/1051
=> [Pirate Ship] Verify return path (Postmark)

hackclub.com.yaml
added bbss.hackclub.com
route https://bbsshackclub.vercel.app/ to https://bbss.hackclub.com (since anything ending with hackclub.com will give us more legitimacy) 
added subdomain bbss.hackclub.com so that we can use it for our hack club.
=> Verify bbss.hackclub.com

hackclub.com.yaml
=> Adding bbss.hackclub.com

hackclub.com.yaml
Adding a value in the _vercel section so that we can verify the domain
=> Verify luna.hackclub.com with vercel

hackclub.com.yaml
My hack club application recently got accepted and I'll be using this subdomain to host my club's website!
=> Adding `arsenic.hackclub.com`

hackclub.com.yaml
with ASTRA hackclub website all PR faults removed
with ASTRA hackclub website all PR faults removed
=> Re adding astra.hackclub.com

hackclub.com.yaml
Adding for https://github.com/hackclub/global/pull/112
=> Adding it.hackclub.com

hackclub.com.yaml
Adding these domains for Russian and Ukrainian versions of hackclub.com requested as per [hackclub/global](https://github.com/hackclub/global) and [this pull request](https://github.com/hackclub/global/pull/111)
=> Adding ru.hackclub.com + Adding uk.hackclub.com

hackclub.com.yaml
Adding an Indonesian Translation domain (`id.hackclub.com`)
https://github.com/hackclub/global/pull/110
=> Adding id.hackclub.com

dino.icu.yaml
Firstly, I apologise if the format is incorrect, I wasn't sure how to add multi level subdomains.
[Vortex](https://vortex-email.vercel.app) is a disposable email service I'm running. The subdomain would be used for:
- The frontend
- The SMTP server
- The backend API
Thanks!
=> Adding vortex.dino.icu

dino.icu.yaml
This will be used for my project "Weather Somewhere" (https://weathersomewhere.netlify.app), a website that displays the weather for a random location, with its population.
=> Adding weather.dino.icu

hackclub.com.yaml
Added Golden to hackclub.com.yaml
Golden is a Days of Service event part of the [Athena](https://athena.hackclub.com/events) intiative
=> Adding golden.hackclub.com

dino.icu.yaml
Add url.dino.icu, the future domain for a public URL shortener found at url.felixgao.dev. That domain will serve as the landing page for the shortener with url.dino.icu being the shortened link provided. For now, I'm using url.felixgao.dev which is much longer (kinda defeats the point of a shortened URL lol).
=> Adding url.dino.icu

hackclub.com.yaml
A CDN subdomain for my club's website
=> Adding `cdn.arsenic.hackclub.com`

hackclub.com.yaml
A link subdomain for my club's website
=> Adding `link.arsenic.hackclub.com`

dino.icu.yaml
A subdomain for my personal site, main URL is https://ssmidge.xyz
=> Added ssmidge.dino.icu

hackclub.com.yaml
Adding GitHub Pages Verification for `arsenic.hackclub.com`
=> Adding `_github-pages-challenge-arsenobetaine.arsenic.hackclub.com`

dino.icu.yaml
this subdomain will be used for my personal developing portfolio
=> Addding dast.dino.icu

dino.icu.yaml
This updates the DNS records for vortex, and adds two more aliases for shadow and erdtree
=> Adding `shadow.dino.icu`, adding `erdtree.dino.icu`, fixing `vortex.dino.icu`

hackclub.com.yaml
Verification for my club's GitHub organization!
=> Adding `_gh-arsenobetaine-o.hackclub.com`

hackclub.com.yaml
We made a new website and its being hosted on vercel
adding the txt verificaition and the cname thingy
=> Updating ocsa.hackclub.com

dino.icu.yaml
#Adding mthlpbs.dino.icu
Uses as my personal website (portfolio, blog and etc)
=> Add mthlpbs.dino.icu

hackclub.com.yaml
This domain will be used as the website for Osbourn Park High School's Hack Club and TSA.
=> Adding subdomain op

hackclub.com.yaml
The address returns an SSL error so I am updating the domain to match with the [Nest documentation](https://guides.hackclub.app/index.php/Subdomains_and_Custom_Domains).
=> Change op.hackclub.com so that the address will work with Caddy

hackclub.com.yaml
Adding a subdomain for my club's website!
=> Adding `pinetree.hackclub.com`

hackclub.com.yaml
The Persian subdomain for Hack Club
=> Adding `fa.hackclub.com`

hackclub.com.yaml
<https://github.com/hackclub/shipment-viewer>
=> Adding shipment-viewer.hackclub.com

hackclub.com.yaml
The subdomain will be used to host my club's information page so that people can sign up and learn more (https://ecolint-hackclub.vercel.app)
=> Adding `ecolint.hackclub.com`

hackclub.com.yaml
For my school's hack club website
=> Adding milton.hackclub.com

hackclub.com.yaml
Nest is scheduled to go down very soon so I moved the website to an alternative server
=> Updating op.hackclub.com to point to alternate server ahead of Nest maintenance

hackclub.com.yaml
#Adding for-reviewers.hackclub.com
##I and few others(given credits at the bottom of page) made a website to show a small gesture of love for Reviewer's hard work
It will be used for hosting my website that is for the reviewers here is the git pages link https://souptik-samanta.github.io/final-for-arcade/index.html
=> Adding for-reviewers.hackclub.com

hackclub.com.yaml
Our school blocked [our club website](https://optsa.club) so this will server as a mirror for said website.
=> Updating op.hackclub.com to be a domain mirror of our club's blocked domain

hackclub.com.yaml
For the 10 hours of code event
=> Adding waka.hackclub.com

hackclub.com.yaml
A WIP website for ACT Hack Club
=> Added DNS Records For act.hackclub.com

hackclub.com.yaml
1. Updating verification for my club's GitHub organization because the username has been changed.
2. Deleting `cdn.arsenic.hackclub.com` since it's no longer useful.
=> Updating `arsenic.hackclub.com`

hackclub.com.yaml
adding matchups for a hq project cc: @polytroper
=> Add matchups

hackclub.com.yaml
Adding page for Celestial, Toronto's Days of Service event!
=> Adding celestial.hackclub.com

hackclub.com.yaml
=> [Updating]  `waka.hackclub.com`

hackclub.com.yaml
=> Adding counterspell.hackclub.com

hackclub.com.yaml
Oops, forgot to verify on Vercel... apologies.
=> Add Vercel domain verification

hackclub.com.yaml
Halloween is coming, and so is The Spooky Boba Manor; this event will start in October and will be for Hack Clubers to make a manor!
=> Adding manor.hackclub.com

hackclub.com.yaml
This subdomain will be used for our school's Hack Club (John Hersey High School). Eventually, it will be updated around every week to have Hack Club members go to the site.
=> Adding hersey.hackclub.com

hackclub.com.yaml
A YSWS project to obtain a second OnBoard grant, running this October Halloween month
=> Adding showcase.hackclub.com

hackclub.com.yaml
=> Adding verify.onboard.hackclub.com

hackclub.com.yaml
=> Updating `waka.hackclub.com`

hackclub.com.yaml
A club website for my school's club!
=> Added wggs for my school's club

hackclub.com.yaml
Reverts hackclub/dns#1343 cc @Dragon863 I'm reverting this to figure out what's up in production with your records– will reapply them once I can!
=> Revert "Add domain verification for runshaw.hackclub.com"

hackclub.com.yaml
See https://github.com/hackclub/dns/pull/1347
=> Attempt to re-add TXT record from #1343

hackclub.com.yaml
=> Revert "Attempt to re-add TXT record from #1343"

hackclub.com.yaml
Adds new YSWS verification API for onboard verification form
=> Adding api.onboard.hackclub.com

hackclub.com.yaml
For the new easy shipping program which allows people to easily ship and track internationally, for clubs and certain YSWS.
=> Adding `shipping.hackclub.com`

hackclub.com.yaml
This will be used for a Hack Club Minecraft minigames server. It's created for SAD but will be public for anyone to use.
=> Adding `minigames.hackclub.com`

hackclub.com.yaml
Added MX and SPF records for Google Workspace.
=> Updating `counterspell.hackclub.com`

hackclub.com.yaml
=> Revert "Update op.hackclub.com"

hackclub.com.yaml
=> Revert "Updating `counterspell.hackclub.com`"

hackclub.com.yaml
Adding Agra Hack Club, site custom made for upcoming Counterspell hackathon.
=> Add Agra Hack Club

hackclub.com.yaml
Adding busan.hackclub.com for Hack Club Busan for South Korea.
=> Add busan.hackclub.com.

hackclub.com.yaml
Related to #1354
See [Slack thread ](https://hackclub.slack.com/archives/C05SVRTCDGV/p1728883304661009)
Please merge #1362 after this one has deployed.
=> Remove counterspell.hackclub.com

hackclub.com.yaml
Related to #1354
See [Slack thread](https://hackclub.slack.com/archives/C05SVRTCDGV/p1728883304661009)
Please merge after #1360 has been deployed.
=> Add counterspell.hackclub.com

hackclub.com.yaml
=> Revert "Add Agra Hack Club"

hackclub.com.yaml
=> Adding cascade.hackclub.com

hackclub.com.yaml
Subdomain for the Wesley Hack Club website.
=> Adding `wesley.hackclub.com`

hackclub.com.yaml
A website for a school Hack Club. Not much content for now, but will be improved over time!
=> Adding osca.hackclub.com

hackclub.com.yaml
Subdomain will be used for HCB blog/engineering site. Currently a work-in-progress but the domain is needed to test CORS issues.
=> Add blog.hcb.hackclub.com

dino.icu.yaml
using cname instead of "A" for Vercel 
Thx for the help @alx-alexpark
=> Adding aryanpatel.dino.icu

dino.icu.yaml, hackclub.com.yaml
- made all suggested changes.
- thanks for helping @alx-alexpark
=> Adding `heramb.dino.icu`

hackclub.app.yaml
This PR configures DKIM for the nest VM and makes DMARC reports go to an address that currently forwards to a dedicated slack channel for analysis.
=> Adding `nest2024._domainkey.hackclub.app`

hackclub.com.yaml
=> add innkeeper.hackclub.com

dino.icu.yaml
=> Adding `firepi.dino.icu`

hackclub.com.yaml
Adding arcade-wrapped.hackclub.com for the [Arcade Wrapped](https://www.arcade-wrapped.netlify.app) site!
=> Adding arcade-wrapped.hackclub.com

hackclub.com.yaml
Refactor from a previously approved PR - just changing order! cc. @alx-alexpark
=> Adding contact-helper.hackclub.com

hackclub.com.yaml
=> hackclub.com: add high-seas -> highseas redirect

dino.icu.yaml, hackclub.com.yaml
Will be used for spotify.neon.hackclub.app
a community built hackclub playlist.
=> feat(domain): spotify.hackclub.com

dino.icu.yaml
Adding so I can more easily share projects hosted on a server I have setup
=> Add evan subdomain to dino.icu.yaml

dino.icu.yaml
Added a CNAME for overflow.dino.icu pointing to overflow.craigg.hackclub.app. This will be used for Hack Overflow, a Q&A system for Hack Club
=> Adding `overflow.dino.icu`

dino.icu.yaml
This is for a subdomain generator, which generates a random free subdomain for anyone who uses it from a list of all my domains.
=> Adding subdomain.dino.icu

hackclub.com.yaml
Anchor is a new YSWS tied to High Seas
=> Adding anchor.hackclub.com

dino.icu.yaml
It will host https://github.com/dispherical/hacknote on Nest.
=> Adding hacknote.dino.icu

hackclub.com.yaml
=> add parcel-pyxis

wackclub.com.yaml
This is to get around keyword block lists for schools
=> Adding waka.wackclub.com

hackclub.com.yaml
Added the following to hackclub.com.yml in order to get constellation.hackclub.com live
```
constellation:
ttl: 600
type: CNAME
value: cname.vercel-dns.com.
```
It will be used for main page of constellation, a self-hosted webpage YSWS I'm developing
=> [Adding] `constellation.hackclub.com`

dino.icu.yaml
=> Updating social.dino.icu

hackclub.com.yaml
Adds google site verification TXT record to counterspell.hackclub.com for Google Search Console use.
=> Add google site verification to counterspell.hackclub.com

dino.icu.yaml
Adding https://heramb0x1.github.io/betterwork-ai/ under dino.icu subdomain
=> Adding `betterwork-ai.dino.icu`

hackclub.com.yaml
DNS records added for Synthax  a newly founded club at hackclub
=> Adding synthax.hackclub.com

dino.icu.yaml, hackclub.com.yaml
adding avsc.dino.icu, for hosting my personal website soon. currently the weather app i created is hosted here. pls approve.
=> Adding avsc.dino.icu

dino.icu.yaml
=> Updating betterwork-ai.dino.icu

hackclub.com.yaml
We are adding this subdomain for the fraser hack club website (WIP).
=> Adding`fraser.hackclub.com`

hackclub.com.yaml
Remove shipping.hackclub.com as it is not an hq project
=> Remove shipping.hackclub.com as it is not an hq project

hackclub.com.yaml
#adding `teenverse.hackclub.com`
i want to show the affiliation of hack club in my club so i thought would be better if i got with subdomain rather than a seperate domain. also it will be easier for everyone to learn more about hack club this way
=> Adding teenverse.hackclub.com

hackclub.com.yaml
Used for the hacky holidays pcb event
=> Addding Hackyholidays.hackclub.com

hackclub.com.yaml
Adding `aswhackclub.hackclub.com
A new hack club is starting at the American School of Warsaw, so we are getting aswhackclub.hackclub.com
=> Add the ASW hack club from Silverflag's vps IP

hackclub.com.yaml
=> Add hackstone

hackclub.com.yaml
This PR adds the BakeBuild subdomain for the BakeBuild YSWS approved by @grymmy.
=> Adding subdomain `bakebuild.hackclub.com`

hackclub.com.yaml
This adds a subdomain for https://github.com/hackclub/YSWS-Catalog
=> Add ysws.hackclub.com

hackclub.com.yaml
Updating destination from kaympe20.github.io. to bakebuild.hackclub.com
=> Updating bakebuild.hackclub.com

hackclub.com.yaml
The Hack Mic's Website
thehackmic.hackclub.com
=> Adding thehackmic.hackclub.com

hackclub.com.yaml
Updating asw.hackclub.com
Added the google verification to the domain.
=> Updating asw.hackclub.com

hackclub.com.yaml
=> Adding printboard.hackclub.com

hackclub.com.yaml
=> add firehose.hackclub.com

hackclub.com.yaml
Hi hello this will be for asylum, a group of hardware-focused yswses at hc
=> [Adding] `asylum.hackclub.com`

dino.icu.yaml
removing / deleting a sub-domain,
thanks!
=> # Deleting `betterwork-ai.dino.icu`

hackclub.com.yaml
Add Scrapyard Google Workspace records
=> Add Scrapyard Google Workspace

hackclub.com.yaml
=> Add slack-id.hackclub.com

dino.icu.yaml
=> Deleting `heramb.dino.icu`

hackclub.com.yaml
This PR can be reverted once highseas.hackclub.com is back up!
=> Switch to high seas maintenance page temporarily

hackclub.com.yaml
Updating the Official Dessert YSWS landing page url here from vercel for netlify.
=> Updating dessert.hackclub.com

hackclub.com.yaml
=> move warehouse infra over to self-hosted!

hackclub.com.yaml
This is for the raspapi YSWS in #raspapi-ysws
=> Add raspapi.hackclub.com

hackclub.com.yaml
https://hackclub.slack.com/archives/C0C78SG9L/p1736566910720719?thread_ts=1736549529.194619&cid=C0C78SG9L Removing this so we don't confuse people– this is no longer maintained
=> Remove directory.hackclub.com

dino.icu.yaml
Setting up a [Wikibase Cloud](https://www.wikibase.cloud/) instance for the Hack Club community via custom domain setup. Will set up a Slack channel afterwards.
Official docs: https://www.mediawiki.org/wiki/Wikibase
=> chore(dino.icu): add wikibase.dino.icu DNS records

hackclub.com.yaml
add hackclub Vidisha's website
src: https://github.com/arjav0703/hackclub-vidisha
=> Adding vidisha.hackclub.com

hackclub.com.yaml
Used for Orpheus Pico. Approved by G
=> Adding orpheuspico.hackclub.com

hackclub.com.yaml
YSWS, please approve :3333 (#hackapet)
=> Adding hackapet.hackclub.com

hackclub.com.yaml
=> add conduct.hackclub.com emails

hackclub.com.yaml
=> fix error for conduct

hackclub.com.yaml
=> Add google site token for DevHacks

hackclub.com.yaml
Website for an asylum ysws. doing some restructuring
=> [Adding] `raincloud.hackclub.com`

hackclub.com.yaml
=> adding juice.hackclub.com

bank.engineering.yaml
=> [Updating] `gverify.bank.engineering`

hackclub.com.yaml
Updating printboard to move to vercel and adding tag, another asylum YSWS
=> [Updating/Adding] updating `printboard.hackclub.com` and adding `tag.hackclub.com`

hackclub.com.yaml
Added hackatsst.hackclub.com
For public to see information on the hack club I'm organising as well as access the member's portal
=> Added hackatsst.hackclub.com

hackclub.com.yaml
Reverts hackclub/dns#1512
Fingers crossed this worked!
=> Revert "Switch to high seas maintenance page temporarily"

hackclub.com.yaml
As part of migration of Bag to Coolify
=> add bag-api.hackclub.com

hackclub.app.yaml
Migrating uptime kuma to nest-logs
=> Add logs and status

hack.club.yaml
=> Revert "Modifying hack.club to use coolify now as well"

dino.icu.yaml, hackclub.com.yaml
Currently just my portfolio site I made during Arcade but I plan to use it as the main demo link for future hackclub projects and move existing HighSeas Projects in directories
=> sayhan rahman

hackclub.com.yaml
=> [Updating] `mfa.hackclub.com`

hackclub.com.yaml
Migrate Professor Bloom to Coolify
=> migrate professor bloom to coolify

hackclub.com.yaml
https://github.com/hackclub/coolify-slack-conductor
=> [Adding] coolify-conductor.hackclub.com

dino.icu.yaml
Will host my school's forum ruining nodebb
=> Adding hasd.dino.icu

hackclub.com.yaml
=> Shorten Hackathons' TTL for migration to Coolify

hackclub.com.yaml
=> Point dash.hackathons.hackclub.com to Coolify server A

hackclub.com.yaml
This is a domain for an upcoming [trail](https://trail.hackclub.com/)-style hackathon, Intranet.
=> Add intranet.hackclub.com

hackclub.com.yaml
Adding jua.hackclub.com
This is for the Nairobi Athena Event in March, Jua.
=> Adding jua.hackclub.com

hackclub.com.yaml
Trying to see if using Vercel will make it work since Netlify doesn't :) (sorry!)
=> Updating jua.hackclub.com

hackclub.com.yaml
=> Vercel verification multiverse hackclub.com.yaml

hackclub.com.yaml
Adding infill, a YSWS where you design a 3D printer, and i'll ship the parts to you
=> [Adding] `infill.hackclub.com`

hackclub.com.yaml
Switching Arrpheus to be hosted from Coolify
(also, there's a few extra commits in here because I forgot how GitHub works - they shouldn't do anything, the only thing changed is the domain in question)
=> Updateing hsi.hackclub.com - switch Arrpheus to Coolify

hack.af.yaml, hackclub.app.yaml
=> Add Scrapyard ticketing

hackclub.com.yaml
=> Add `ingress.hcb.hackclub.com`

hackclub.com.yaml
Currently at 1 hour, changing it to 1 sec.
=> Decrease TTL of `hcb.hackclub.com`

hackclub.com.yaml
=> Add `hcb-test.hackclub.com`

hackclub.com.yaml
=> Add ACME challenges for `hcb.` and `hcb-test.`

hackclub.com.yaml
=> Revert "Move sprig to coolify and remove some old aliases"

hackclub.com.yaml
=> Revert "Revert "Move sprig to coolify and remove some old aliases""

hackclub.com.yaml
Make it an ALIAS to match `hcb.hackclub.com` and make ttl 1
=> Edit `hcb-test.hackclub.com`

hackclub.com.yaml
=> Switch `hcb.hackclub.com` to Coolify!

hackclub.com.yaml
I built a new website with Next.js (using hackclub's theme-starter) and want to switch from GitHub Pages to Vercel and made the required changes. The source code of both of the websites is at [github](https://github.com/orgs/HackClub-Vidisha/repositories)
=> Updating vidisha.hackclub.com

hackclub.com.yaml
It seemed to have worked before...
¯\_(ツ)_/¯
=> Try and fix Scrapyard DMARC

dino.icu.yaml
Gonna use it for my personal website deployed using Vercel
=> ADD arjav.dino.icu

hackclub.com.yaml
Added a subdomain for an event, please DM for details.
=> Adding apex.hackclub.com

hackclub.com.yaml
This will be the website for my Hack Club. Let me know if I did this right🙏
=> Add imperial.hackclub.com

hackclub.com.yaml
Update to the DNS for the new STEM EGYPT Hack Club website.
=> Update to the DNS for the new STEM EGYPT Hack Club website.

hackclub.com.yaml
Adds `mchs.hackclub.com` as a subdomain which is for [Hack Club MCHS](https://www.instagram.com/mchspc/). Moving to Hack Club's DNS allows us to stop paying for our current domain at [mchspc.com](https://mchspc.com/).
=> Adding `mchs.hackclub.com`

hackclub.com.yaml
updating `blackbox.hackclub.com`
=> point blackbox to Coolify

hackclub.com.yaml
These are the records for sending SES email from timedump.hackclub.com
=> Add timedump dmarc + dkim records

dino.icu.yaml
Change CNAME to my DuckDNS that points to my homelab instead using my domain (since I want to proxy all my domain, so I fallback to my Dynamic DNS for retro site!)
=> [Updating] toonnongaeoy.dino.icu to DuckDNS point to my Homelab instead.

hackclub.com.yaml
Adds the verification for the `mchs.hackclub.com` domain for our [hackclubmchs](https://github.com/hackclubmchs) organization on GitHub.
=> Adding `_gh-hackclubmchs-o.mchs.hackclub.com`

hackclub.com.yaml
=> Add vercel verification for pixeldust

hackclub.com.yaml
=> Setup hackatime subdomain

hackclub.com.yaml
Added my Hack Clubs current site and will be used for our hack club :)
=> [Adding 'wshackclub.hackclub.com']

hackclub.com.yaml
Point `hcb-test.hackclub.com` to Hatchbox (Hetzner LB). Set HCB TTL to 1 in prep for move.
=> [Add] `hcb-test.hackclub.com`

hackclub.com.yaml
I've added Hack Club spaces previously at https://spaces.learnwillow.org/ for the beta to prod, https://spaces.hackclub.com/. Please DM me on slack with any questions! https://hackclub.slack.com/team/U08BH57AZKP
Don't know what this is? Join #spaces
=> Add Hack Club Spaces as a subdomain

hackclub.com.yaml
Their crawling is causing high load on HCB. I'm claiming ownership of the site on Yandex to change their crawl rate.
=> Add Yandex verification

hackclub.com.yaml
See https://github.com/hackclub/dns/pull/1605
=> Add yandex verification for HCB

hackclub.com.yaml
I'm adding meltdown.hackclub.com, a community hackathon happening in Phoenix, Arizona. @zrl approved this!
=> Adding meltdown.hackclub.com

hackclub.com.yaml
Make the proxyparty thing work again- it broke when conduct.hackclub.com emails were created
=> [Updating] conduct.hackclub.com

hackclub.com.yaml
It is my club name soo we need that subdomain
=> Adding scriptingnest.hackclub.com

hackclub.com.yaml
Adding pa.hackclub.com for Punjabi Translation
=> add punjabi translation domain: pa.hackclub.com

hackclub.com.yaml
This is for the newspaper team!
=> Add newspaper.hackclub.com

dino.icu.yaml
I will be using this subdomain to host my knowledgebase. note: i am already using the arjav.dino.icu subdomain
=> [ADDING] knowledgebase.arjav.dino.icu

dino.icu.yaml
=> Adding srbns.dino.icu

dino.icu.yaml
This is used for a via to my personal website. I have a Belgian nationality, so i want this subdomain :)
=> Update dino.icu.yaml with waffle.dino.icu

hackclub.com.yaml
new ysws!
sorry for merging without review cara lol
=> adding rpg.hackclub.com

dino.icu.yaml
Just updating to a new IP! I think I put the wrong one in here last time
=> Update evan.dino.icu subdomain to be the correct IP

hackclub.com.yaml
=> mail.hackclub.com -> coolify

hackclub.com.yaml
Hey! 
Approved YSWS - @maxwofford approved the creation of the sudomain :))
Lemme know if you have any queries, just DM me on @/karthik on slack
=> Adding visioneer.hackclub.com

dino.icu.yaml
Used for the Nest Factorio server (#factorio)
=> Adding `factorio.dino.icu`

hackclub.com.yaml
moving `athena.hackclub.com` from vercel to coolify
(@kyraezikeuzor)
=> pointing athena.hackclub.com to coolify

hackclub.com.yaml
After this is merged, we will all cool down!!
=> Adding Swirl YSWS

hackclub.com.yaml
=> Adding vote.visioneer.hackclub.com

dino.icu.yaml
Adding a subdomain for our proxy service so we can have the dashboard behind a https cert
=> Adding `proxy.you-ship-we-vote.dino.icu`

dino.icu.yaml
We just changed hosts for the Factorio server - updating to to the new one.
Original PR: https://github.com/hackclub/dns/pull/1602
=> Updating `factorio.dino.icu`

hackclub.com.yaml
This updates intranet.hackclub.com to use Cloudflare Pages instead of Github Pages as Cloudflare Pages is much faster.
=> Update `intranet.hackclub.com` to use Cloudflare Pages

dino.icu.yaml
=> Revert "Updating `factorio.dino.icu`"

dino.icu.yaml
Moving to a new host - need to replace a CNAME with an A record
PR 1 of 2
https://hackclub.slack.com/archives/CS8TQ86GN/p1743130919278049
=> Deleting `factorio.dino.icu`

hackclub.com.yaml
Updates `mchs.hackclub.com` to GitHub Pages instead of Vercel. I want to do this because Vercel costs for deploying in a GitHub organization without workflows. I want students to easily be able to deploy their site to our subdomain without needing to figure out Vercel.
=> Updating `mchs.hackclub.com`

hackclub.com.yaml
=> Add the-pier.hackclub.com

hackclub.com.yaml
(i apologize for all the emails)
=> Add pier and jitsi.pier

hackclub.com.yaml
This is a draft for now while the coolify deploy is being setup
=> Switch spaces.hackclub.com to coolify

hackclub.com.yaml
=> Revert "Switch spaces.hackclub.com to coolify"

hackclub.com.yaml
See https://github.com/hackclub/dns/pull/1633#issuecomment-2764874404 for context
=> Remove spaces while fixing prod deployment

hackclub.com.yaml
See https://github.com/hackclub/dns/pull/1633#issuecomment-2764874404 for context
=> Add in coolify CNAME for spaces.hackclub.com

hackclub.com.yaml
A new YSWS, please DM `@Gao Felix` on the slack if you have questions :D
=> Add pinecone.hackclub.com

hackclub.com.yaml
=> add caffeinecrash

hackclub.com.yaml
=> Adding you-ship-we-clip.hackclub.com

hackclub.com.yaml
The top-secret YSWS project is beyond anything you could possibly imagine. It’s big—bigger than big. It’s something that’s never been done before, something so revolutionary that it will change everything. You won’t see it coming, but when it arrives, you’ll know.
People have speculated, but no one really knows. The scale? Unprecedented. The impact? Unimaginable. The details? Well, those are locked away, deep beneath layers of secrecy. But trust me—when it’s revealed, nothing will ever be the same again.
It’s happening. It’s real. And when the time is right, you’ll understand.
=> Adding `sketchglow.hackclub.com`

hackclub.com.yaml
=> correct domain

hackclub.com.yaml
for the ysws - this is not an april fools joke :pf:
=> Add solder.hackclub.com

hackclub.com.yaml
[Adding] `panorama.hackclub.com`
Explained in DM to @alx-alexpark
=> [Adding] panorama.hackclub.com

hackclub.com.yaml
=> add wormhole

hackclub.com.yaml
Adding waveband.hackclub.com for the Waveband YSWS website. This is HQ approved.
=> Adding waveband.hackclub.com

hackclub.com.yaml
=> add hcpcxc

hackclub.com.yaml
=> Add journey.hackclub.com

hackclub.com.yaml
This is for the video conversion server for our hosted vert.sh instance
=> Add convert-backend

hackclub.com.yaml
Moving my [shields.io Hackatime wrapper](https://github.com/pbhak/hackatime-badge) here!
=> Adding hackatime-badge.hackclub.com

hackclub.com.yaml
=> Add Aurora dos

hack.club.yaml, hackclub.com.yaml
Adds the subdomain largo.hackclub.com. This website is used for the Largo High School Coding Club as their official website.
=> Adding largo.hackclub.com

hackclub.com.yaml
hi, leeks team! give me 10 minutes...
=> Adding tonic.hackclub.com

dino.icu.yaml
=> Add {sequoia,dash}.dino.icu

hack.af.yaml, hack.club.yaml
=> Setting up Shipwrecked Redirect Site

dino.icu.yaml, hackclub.com.yaml
I added my DNS records in the dino.icu.yaml file.
This subdomain is intended to host my personal website hosted on Vercel
=> Adding `shammah.dino.icu` subdomain

hackclub.com.yaml
Using for the upcoming toppings event, sponsored by @jaredsene.
=> Adding toppings.hackclub.com

hackclub.com.yaml
adding subdomain for the days of service event, underground
=> adding underground days of service event

hackclub.com.yaml
adding a subdomain for keepsake, a singapore workshop-hackathon event happening in june, organized by me (tongyu) and kai ling. sponsored by hack club/officially a hc event :)
(i think i can only link up the domain properly in nest after the dns propagates right?)
=> add keepsake.hackclub.com

hackclub.com.yaml
Hack Club MCHS no longer is a club, and we don't need a website for this reason. [Our GitHub organization](https://github.com/hackclubmchs) is archived, and we want to clean up the DNS.
=> Deleting `mchs.hackclub.com`

hackclub.com.yaml
Does #1514 while fixing any previous merge conflicts
=> remove dangling cnames & netlify/github takeovers take 2

hackclub.app.yaml
This PR adds a forward DNS record for `minio.hackclub.app` corresponding with the reverse DNS record previously added on Hetzner.
=> Add minio.hackclub.app to hackclub.app.yaml

hackclub.com.yaml
=> Add idea.shipwrecked.hackclub.com

hackclub.com.yaml
Donor graphs! https://github.com/hackclub/hcb-donor-graph
=> Add graph.hcb.hackclub.com

hackclub.com.yaml
YSWS where we ship Junk Food, HQ sponsor: Jared.
=> Adding grub.hackclub.com

hackclub.com.yaml
This is for highway, the general hardware YSWS leading into undercity
=> [Adding] `highway.hackclub.com`

hackclub.com.yaml
=> add hardware.hackclub.com

hackclub.com.yaml
=> add athena project

hackclub.com.yaml
Adding organizer.hackclub.com
a ysws organizer faq site
=> Adding ysws organizer site 

hackclub.com.yaml
=> adding bridgeportohio and www.bridgeportohio

hackclub.com.yaml
oops sorry, forgot to add the txt record for vercel, my bad
=> Updating fhs.hackclub.com

hackclub.com.yaml
adding express, a guide to express
@pivilartisant
=> add express

hackclub.com.yaml
registering award.hackclub.com just in case
=> adding award.hackclub.com

hackclub.com.yaml
I'm one of the new mc admins. We're moving the minecraft server to a better infra, and this requires an update in the DNS records.
=> [Updating] `mc.hackclub.com`

hackclub.com.yaml
=> Revert "[Updating] `mc.hackclub.com`"

hackclub.com.yaml
=> remove mc records

hackclub.com.yaml
Adding passport
HQ project
manager @maxwofford @JaredSene
=> Adding passport.hackclub.com

hackclub.com.yaml
Newspaper Team project -- DM me (@mahad) if you need more info
=> Add letters.hackclub.com

hackclub.com.yaml
moving from canva to vercel :)
=> hc organizer

hackclub.com.yaml
=> Replace letters.hackclub.com with news.hackclub.com

hackclub.com.yaml
Adding website for JPEG game jam, an Athena event
=> Adding jpeg.hackclub.com

hackclub.com.yaml
We're moving to Vercel!
This is a Newspaper Team project - DM me (@mahad) on the Slack if you need more details!
=> Move to Vercel!

hack.club.yaml, hackclub.com.yaml
Adding:
my.hack.club
dashboard.hackclub.com
clubdash.hackclub.com
(from coolify)
------------------
@ jps on slack for permission
=> Add club dash subdomains

hackclub.com.yaml
Domain will be used for the clubs website
=> # [Adding/Deleting/Updating] `subdomain.[hackclub.com/dino.icu/etc]`

hackclub.com.yaml
Some performance issues with Vercel so moving to my own server hosted in Germany at [PawHost](https://pawhost.de/en/)!
=> Updating pfp.hackclub.com

hackclub.com.yaml
Adding it back after #1787 cuz DNS
=> Adding pfp.hackclub.com

hackclub.com.yaml
Adding subdomain for AlexHack club website an official hack club
=> AlexHack club website addition

hackclub.com.yaml
explorpheus :) dm for any quesions
=> add explorpheus

hackclub.com.yaml
This domain will be used for the Illumination YSWS, as part of the YSWS Combinator.
=> Adding `illumination.hackclub.com`

dino.icu.yaml
Looking to host a personal website on a VPS.
=> Adding krishnan.dino.icu

hackclub.com.yaml
We want to use the kerala.hackclub.com subdomain for running a hackclub community in kerala.Yes I have noted that there has been previous usage of the above subdomain though it seems to have not served its purpose completely and the previous PR's are now working jobs so I hope us taking this subdomain is possible
=> Updating kerala.hackclub.com

hackclub.com.yaml
It will be Used as HackClub Butwal's Domain. Club Located at Butwal , Nepal.
=> Add CNAME record for `butwal.hackclub.com` pointing to Vercel DNS

dino.icu.yaml
updating my redirect to home server to reflect my updated ip address, which has changed.
=> Updating `yates.dino.icu`

hackclub.com.yaml
=> Add: comms

hackclub.com.yaml
:3c:
HQ project. Please DM me if you need more details :)
=> Add Converge

hackclub.com.yaml
I’m adding the subdomain `1or0.hackclub.com` to point to my website hosted on Vercel at `1or0.vercel.app`.
This is the site for Bal Bharati Public School Rohini Hack Club
Thanks
=> Adding 1or0.hackclub.com

hackclub.com.yaml
=> Adding `identity.nephthys.hackclub.com` & `summer.nephthys.hackclub.com`

hackclub.com.yaml
=> adding cinema dns

hackclub.com.yaml
Linking squeak.hackclub.com, an upcoming mouse YSWS
=> Adding `squeak.hackclub.com`

hackclub.com.yaml
=> Added extensify - works

hackclub.com.yaml
add jumpstartv1.hackclub.com for old version and jumpstart.hackclub.com for version 2
=> add jumpstartv1.hackclub.com and jumpstart.hackclub.com

hackclub.com.yaml
Adding `smelt.hackclub.com`
Soon 👀
=> Add `smelt.hackclub.com`

hackclub.com.yaml
=> Adding plunge.hackclub.com 2

hackclub.com.yaml
Adding hackfinger.hackclub.com
I am a summer intern and this website will be used for an upcoming YSWS.
=> Adding hackfinger.hackclub.com

hackclub.com.yaml
=> add railway

hackclub.app.yaml
This introduces a `pbx.hackclub.app` domain, as part of an internal nest project.
=> Add pbx.hackclub.app

hackclub.com.yaml
The little boy clutched an old clock in his palm. Its hands glowed with a strange neon light. Curious, he twisted them backward..... And suddenly, the room shuddered, colors flickered like a VHS tape, and time itself seemed to rewind.
Welcome to Retro Rewind..... 🕒
=> retro rewind

hackclub.com.yaml
Add subdomain for new overflow: hidden; ysws
=> Adding overflow-hidden.hackclub.com

hackclub.com.yaml
Infra for YSWS's and anything else that we want id verification for
=> Adding submit.hackclub.com

hackclub.com.yaml
Staging environment for YSWS Identity Vault integration
=> Adding staging.submit.hackclub.com

hackclub.com.yaml
=> Add jet.hackclub.com

hackclub.com.yaml
Added disconnect to hackclub.com
=> Update hackclub.com.yaml - for disconnect

hackclub.com.yaml
=> reality.hackclub.com

hackclub.com.yaml
=> Move daydream back to vercel

hackclub.com.yaml
=> Move Daydream back to Coolify

hackclub.com.yaml
=> Revert "Update hackclub.com.yaml"

hackclub.com.yaml
List of all webdev ysws and a base schedule for leaders to go by if they decide to run these webdev YSWS.
This is approved by HQ
=> Add schedule.webdev and webdev

hackclub.com.yaml
=> [HCB] Add new DNS challenge for SSL

hackclub.com.yaml
The Summer of Making shell leaderboard, currently residing at https://som-lb.cyteon.dev
=> Adding lb.summer.hackclub.com

hackclub.com.yaml
=> Added optimize

hackclub.com.yaml
pls accept 🥺
undercity recap site!!!!!
=> add undercity.hackclub.com

hackclub.com.yaml
=> Updating hackclub.com.yaml

hackclub.com.yaml
=> Remove lb (temporaily)

hackclub.com.yaml
Removed and added back, to update records cause deploy failed on update
=> Add lb back

hackclub.com.yaml
=> Adding slushies.hackclub.com

hackclub.com.yaml
Adding bitstream.hackclub.com
For Bitstream YSWS
=> Adding bitstream.hackclub.com

hackclub.com.yaml
Once your fortress has at least 20 dwarves, occasionally one of them will be struck by a "strange mood". These largely random events will be seen as an announcement, and will pause the game.
=> Adding hivemind.hackclub.com

hackclub.com.yaml
switched to an SRV and CNAME record to avoid having to make multiple PR's everytime the IP updates
=> add minecraft records

hackclub.com.yaml
=> Adding tile.hackclub.com

hackclub.com.yaml
=> [Adding] `cmd-k.hackclub.com`

hackclub.com.yaml
Add subdomain for infinity YSWS
=> Adding `infinity.hackclub.com`

hackclub.com.yaml
=> Adding editor.bitstream.hackclub.com

hackclub.com.yaml
=> add shush.hackclub.com

dino.icu.yaml
For my personal website/blog (made for [Swirl](https://swirl.hackclub.com))
=> Adding 'lyon.dino.icu'

hackclub.com.yaml
=> add roulette.hackclub.com

dino.icu.yaml
Add `gyor.dino.icu` for our new Hack Club in Győr (Hungary).
=> Adding gyor.dino.icu

hackclub.com.yaml
I added my ysws site approved by Sam Liu.
=> Adding neohack.hackclub.com

dino.icu.yaml
A project of mine, clash royale stats website
=> Adding cr.dino.icu

hackclub.com.yaml
Updating the neohack domain to the self hosted version
=> Updating neohack.hackclub.com

hackclub.com.yaml
=> Adding fab.hackclub.com

hackclub.com.yaml
To be used for the firmware flasher for the badge at Shipwrecked.
=> Add badge.shipwrecked.hackclub.com

hackclub.com.yaml
Adding subdomain for birthday cards YSWS
=> Adding `birthday-cards.hackclub.com`

hackclub.com.yaml
=> Update hackclub.com.yaml - joe

hackclub.com.yaml
Added a subdomain for Fusering, an upcoming YSWS:  "Design a keyring, get your keyring and a clip for your backpack!" 
HQ Sponsor: Jared
=> Added fusering.hackclub.com

hackclub.com.yaml
=> Update hackclub.com.yaml - touch grass

hackclub.com.yaml
=> [Adding] waveform.hackclub.com

hackclub.com.yaml
Adding cad.hackclub.com, basically to be like webdev.hackclub.com but for cad 
my first dns pr! hope i did this right
yeah thats about it thanks
=> Adding cad.hackclub.com

hackclub.com.yaml
Will merge https://github.com/hackclub/dns/pull/1964 after to add it back with ALIAS
=> Temporarily delete `daydream`

hackclub.com.yaml
=> [Adding] helm.hackclub.com

hackclub.com.yaml
=> add: improving 

hackclub.com.yaml
=> Submit docs

hackclub.com.yaml
For upcoming YSWS, see `#branch` in the Slack.
HQ PoC @JaredSene
=> Adding branch.hackclub.com

hackclub.com.yaml
I'm the new gap year, this is my first YSWS
=> Added CodeQuest to hackclub.com

hackclub.com.yaml
=> Add format.hackclub.com

hackclub.com.yaml
=> updating parthenon.hackclub.com

dino.icu.yaml
It's a thing I'm working on where you send in stickers and they're added into a global stickerboard!
=> add stickerboard.dino.icu

hackclub.com.yaml
=> okay fun time over now back to work

hackclub.com.yaml
=> Switch `bank.hackclub.com` over to Vercel

hackclub.com.yaml
=> Add CNAME record for checkin.daydream.hackclub.com

hackclub.com.yaml
This is the Slack bot for Special Activities Division
=> Add `isabelle.hackclub.com`

hackclub.com.yaml
=> Add CNAME records for b-limited selfhosted domains

hackclub.com.yaml
follow up to https://github.com/hackclub/dns/pull/2048
My mistake! didn't break dns, but my stuff def didn't load!
=> Turns out that wasn't a static IP!

dino.icu.yaml
Use static A records from Deno Deploy (Early Access, not Classic) to allow MX/TXT records use in the future.
See https://github.com/hackclub/dns/pull/1875 for context regarding why it's uncommented.
=> (Re)adding ajhalili2006.dino.icu and andreijiroh.dino.icu

hackclub.com.yaml
New leadership made a new site.  i am said old leader and changing the domain for their new website 👍
Will be used to be our new club website
=> Updating BBSS.Hackclub.com

hackclub.com.yaml
adding HackBerry YSWS as a Gap Year
=> Add HackBerry to hackclub.com

hackclub.com.yaml
=> Add itch.daydream.hackclub.com

hackclub.com.yaml
cc @EDRipper
Needed for new ysws
=> Adding playphone.hackclub.com

hackclub.com.yaml
=> Add gamebit.hackclub.com

hackclub.com.yaml
summer.hackclub.com/s will redirect to island.hackclub.com where i will move the content after SOM ends
=> adding island to .com yaml -surely this time

hackclub.com.yaml
=> Correct hackcraft server

hackclub.com.yaml
=> Add Microsoft verification to root domain

hackclub.com.yaml
Added website for an upcoming YSWS. Approved by @/jps.
=> Add enclosure domain verification and CNAME record

hackclub.com.yaml
I'm moving it from @Navdeep-Codes' account to mine, as I'm taking over the YSWS!
=> Updating waffles.hackclub.com

hackclub.com.yaml
=> moving to coolify
