hackclub/dns

hackclub.com.yaml

Adding The Business Project (TBP) as a HackClub.com subdomain.

Add tbp.hackclub.com

---

hackclub.com.yaml

The modded server doesn't exist anymore so there's no reason to keep this IP here - now it just goes to the vanilla server IP

Update mc.hackclub.com to the vanilla server

---

hackclub.com.yaml

These no longer point to Hack Club-owned IPs.

Remove Pepix Records

---

hackclub.com.yaml

The servers we used are offline now so there's no need to have this here.

Remove fiesta.hackclub.com

---

hackclub.com.yaml

Reverts hackclub/dns#379
This is causing checks to fail

Revert "Add G Suite for tist.hackclub.com"

---

hackclub.com.yaml

So instead of `ssh 34.75.6.116 -p 2222`, people can use `ssh ssh.hackclub.com -p 2222`

Add sshchat.hackclub.com

---

hackclub.com.yaml

This PR adds haas.hackclub.com! Check #hack-as-a-service in Slack for more info

Add haas.hackclub.com

---

hackclub.com.yaml

Reverts hackclub/dns#479
sorry @cjdenio, I think this PR took down the whole domain. Will investigate when I get into the office

Revert "Add haas.hackclub.com"

---

hackclub.com.yaml

Reverts hackclub/dns#480. Attempting to get this back online.

Try to get haas.hackclub.com back online

---

hackclub.com.yaml

Reverts hackclub/dns#481
See previous PR. It took down the website.

Revert "Try to get haas.hackclub.com back online"

---

hackclub.com.yaml

It was not updated to the new Minecraft server's IP yet.

Update the IP for vmc.hackclub.com

---

hackclub.com.yaml

Transfer Domain for Ronald Reagan High School to Organization account and update in Hack Club DNS

Transfer Domain for Ronald Reagan High School

---

hackclub.com.yaml

The following sub-domains have been requested by two Hack Clubs in the APAC region.
This pull request adds them, following are the requested subdomains
1. uet
2. byteclub

add: uet and byte club sub-domains

---

hackclub.com.yaml

This subdomain was originally pointed at our primary org @HackSaimaa, but the repo was moved to @hcksm so thats why this update is necessary.

Update hackclub.com.yaml for saimaa.hackclub.com's new github org

---

hackclub.com.yaml

Added Sub-Domain for Hack Club NUST.
```yaml
nust:
- ttl: 1
type: CNAME
value: club-website-demo2.vercel.app.
```

added nust.hackclub.com

---

hackclub.com.yaml

FYI @leomcelroy / @cedric-h, I'm moving the GitHub Pages hosting for Muse from https://hackclub.github.io/muse / https://muse.hackclub.dev to https://muse.hackclub.com.
Everything should get redirected appropriately, and I'll update the links in the Muse README and links on the GitHub repo too.

Add subdomain for muse.hackclub.com pointing to GitHub Pages

---

hackclub.com.yaml

(set up in Vercel to redirect to gamelab.hackclub.com)
Seems like this [link](https://github.com/hackclub/hackclub/blob/12d22b2355d6e4208254d48f23dae308336ab4c8/workshops/gamelab/README.md?plain=1#L12) in the Workshop links to www.gamelab.hackclub.com which isn't set up currently. This PR adds the CNAME record for that, but I'm not sure if this is desired or if the link in the workshop is just a typo.

Add www.gamelab

---

dino.icu.yaml

It's remarkably difficult to misspell "channel" so consistently.

Add channle.dino.icu

---

dino.icu.yaml

I'm removing the wildcard `*` CNAME record to vercel to prevent abuse. if you're impacted by this feel free to create a PR adding it for your domain.

commenting out the wildcard to vercel

---

hackclub.com.yaml

CC @kpanjolia 
I'd like to use austin.hackclub.com as it seems to be currently unused by the original "claimant" ? I currently run a Hack Club that is open to all teens in Austin, and would like to use austin.hackclub.com as the website address for it.
Thanks!
--reese

Utilize abandondoned domain austin.hackclub.com

---

bank.engineering.yaml

It'd be great if the Hack Club Bank change log was at `changelog.bank.engineering` rather than `changelog.bank.hackclub.com`.
1. Merge this PR
2. Add redirect from `changelog.bank.hackclub.com/$1` to `changelog.bank.engineering/$1`.
3. Make custom domain switch on Headway (https://docs.headwayapp.co/custom-domain)
4. Update widget and links in `hackclub/bank` repo with new domain

Move Bank changelog to `bank.engineering`

---

hackclub.com.yaml

Reverts hackclub/dns#766
The record isn't propagating. Will need to look into this later.

Revert "Add haveibeenpwned TXT verification"

---

dino.icu.yaml

We (#mastodon-dev) decided to use social.dino.icu as the domain name for our mastodon instance.  I am parking it here for now.

Park social.dino.icu

---

hackclub.com.yaml

Remove shop.hackclub.com website / have it redirect to hackclub.com

---

hackclub.com.yaml

Members are having a bit of trouble finding `cchshackclub.hackclub.com`, so I thought it would be easier to shorten it.

Update `cchshackclub` to `cchs`

---

dino.icu.yaml

https://gaming.dino.icu
Website: https://sprig-gaming-controller.vercel.app/

Add subdomain for Sprig gaming controller

---

hackclub.com.yaml

I intend to use this subdomain, libre.hackclub.com, with my Winter of Making project, "[Libre Web Services (LWS)](https://github.com/hackclub/winter/blob/main/alialiwa2005.md)."

Added libre.hackclub.com subdomain

---

hackclub.com.yaml

We don't actively use Segment anymore, so this removes the TXT record that is taking up space

Remove Segment verification

---

hackclub.com.yaml

Heads up, we got an alert from google that this IP might be compromised. If you owned this you might want to check it out.

Remove hn.hackclub.com

---

hackclub.com.yaml

- added SRV record for minecraft for base domain (hackclub.com) -> bedrock would still need mc.hackclub.com:port
- removed SRV, A records for beta-mc.hackclub.com and modded-mc.hackclub.com, both offline

changes to Minecraft Server records

---

hackclub.com.yaml

this still allows minecraft java to access ipv6 (and the admin panel)

minecraft seperate ipv4 and ipv6

---

hackclub.com.yaml

Checkly has a new CNAME domain

Update status.hackclub.com to new Checkly CNAME

---

hackclub.com.yaml

Reverts hackclub/dns#868
Seems like [proxyparty](https://github.com/hackclub/proxyparty) is interfering with this set up. Reverting to the old Checkly dashboard for now

Revert "Update status.hackclub.com to new Checkly CNAME"

---

hackclub.com.yaml

The former TXT record was deleted because:

Add AngelHacks Vercel CNAME

---

hackclub.com.yaml

dash.hackathons.hackclub.com is now being powered by a [Hetzner load balancer](https://www.hetzner.com/cloud/load-balancer), which offers more flexibility.

Change dash.hackathons to load balancer, add server IPs

---

hackclub.app.yaml

Removing proxmox as it is no longer publicly accessible and adding identity to expose Authentik

Nest: Remove proxmox and add identity

---

hackclub.com.yaml

Reverts hackclub/dns#996
Rolling this back temporarily while trying to fix deployments. Sorry @ilyKcaj! It'll get merged back in as soon as we fix this

Revert "Add Boston Latin School (BLS HACK)"

---

hackclub.com.yaml

This is the website for OCSA's Hack Club.  We hope to make this a hub for our clubs resources, including meeting slides and contact information.

OCSA hack club website

---

hackclub.com.yaml

It turns out that you need to use a CNAME record or GitHub will not provision the site at all

Update records for outerlan.hackclub.com

---

hackclub.app.yaml

This routes to the Nest VM on the server, which will be handled by Caddy for Nest users.

Add wildcard for Nest user subdomains

---

hackclub.com.yaml

Organization: https://github.com/ALOPB-Hack-Club
Domain: https://alopb.hackclub.com

Verify ALOPB Hack Club domain for GitHub organization

---

hackclub.com.yaml

Reverts hackclub/dns#1068
This is due to it being a private IP address (10.x range).

Revert "Add Orpheus Odyessy"

---

hack.club.yaml

Fixes an issue where ssl is messed up and host doesn't resolve properly to heroku as a result

Change url to one specifically configured for hack.club in heroku

---

README.md

This PR updates the recommended TTL on the readme from 1 second (no caching) to 600 seconds (10 minutes). Related to #1023

Update README with recommended TTL of 600s

---

hackclub.com.yaml

Reverts hackclub/dns#1094
This PR is causing deploy issues at the moment, due to the invalid CNAME formatting (no pathname in CNAMEs, that's not how they work)

Revert "create pizza.hackclub.com"

---

dinosaurbbq.org.yaml

This PR adds `aux.dinosaurbbq.org` to support the OrpheAUX radio server for hack-night!

Add `aux.dinosaurbbq.org`

---

hackclub.com.yaml

DNSimple doesn't allow ALIAS records to co-exist with other records with the same name

Fix error in hackclub.com.yaml

---

hackclub.com.yaml

HCB's status monitoring has moved to AppSignal. We're setting up a public monitoring dashboard

Adding status.hcb.hackclub.com — HCB Status Page (AppSignal)

---

hackclub.com.yaml

This subdomain will be used for the upcoming Seattle DOS on May 3rd.

Adding evergreen.hackclub.com

---

hackclub.com.yaml

added the entry for cghs.hackclub.com
this will be the subdomain for my highschool's hack club website, where we can provide information and resources, along with links and information on how to join. 
you can check out the existing website at [cghs-hackclub.github.io](https://cghs-hackclub.github.io/). its currently in the process of being updated, and isn't in a fully functional state right now.
Thanks!

Adding cghs.hackclub.com

---

hackclub.app.yaml

Removes summit.hackclub.app, which was used for Summit registration, but is no longer needed on hackclub.app.

Deleting `summit.hackclub.app`

---

hackclub.app.yaml

This PR attempts to fix the Nest SSHFP records again as they seem to have been causing the DNS workflows to fail. These values were generated with `ssh-keygen -r hackclub.app.` and confirmed with `ssh-keyscan -D hackclub.app`.

Updating `hackclub.app`

---

hackclub.com.yaml

Adding a subdomain for Oasis, the Austin (TX) Day of Service.

Adding oasis.hackclub.com

---

hackclub.com.yaml

This change supports email on hcarc.hackclub.com on Migadu as a temporary solution while HCB runs out the google workspace waitlist. When the waitlist is complete, the MX and supporting records will be updated to Google Workspace. Until that happens, only one address will exist to facilitate interactions with the FCC.

Add hcarc.hackclub.com MX and supporting records

---

hackclub.com.yaml

Adding subdomain.forge.hackclub.com #1211
A site for Forge, an upcoming YSWS targeting additive manufacturing and programmatic modeling. You solve a problem using our custom OpenSCAD-based modeling software and you get to build a Forge 3D printer. The Forge is a mostly custom cantilevered printer with a unique motion system and the ability to fold into a filament box. This printer adds features such as ABL, G10, a Sherpa Mini DDE, and WiFi. Featuring a custom engineered mainboard featuring a RP2040 and TMC2209s with a custom firmware.

Adding subdomain.forge.hackclub.com

---

hackclub.app.yaml

This PR:
- updates the AAAA record for `pve.ts.hackclub.app` to reflect reality
- introduces `proxmox.hackclub.app`, which resolves to Nest's proxmox instance's public IP address
- removes two trailing spaces because `nano` was pointing them out

Updating hackclub.app

---

hackclub.app.yaml

Some things still link to it, and it would be good to provide a redirect instead of

Add summit.hackclub.app

---

hackclub.com.yaml

This PR adds a subdomain for OnBoard Live, which will be announced next week. Please [DM @Micha on Slack](https://hackclub.slack.com/archives/D05C64XN2T1) for more info!

Add OnBoard Live subdomain

---

hackclub.com.yaml

This is to verify the `arsenic.hackclub.com` subdomain for the github organization!

Adding `_gh-arsenobetaine-o.arsenic.hackclub.com`

---

dino.icu.yaml

Pardon the Conventional Commits style in the patch/merge request title.
So I am adding my website (it was obvious that I use [Material for Mkdocs](https://github.com/squidfunk/mkdocs-material) for the theming) under both `ajhalili2006` (my username) and `andreijiroh` (first name) subdomains. Please let me know if I should pick either one and I'll amend the commit later.
For technicalities behind the CNAME record, I'll be doing the redirects via my own Caddy config at https://github.com/recaptime-dev/proxyparty-caddy instead of setting up additional custom domains on my Cloudflare Pages project. (The Caddy server in question is hosted on an `e2-micro` GCP Compute Engine instance per https://github.com/recaptime-dev/proxyparty-caddy/blob/main/SETUP.md#gcp-compute-engine-vm.)

chore(dino.icu): Add DNS records for <ajhalili2006|andreijiroh>.dino.icu

---

hackclub.com.yaml

Hello,
@grymmy recently upgraded the OnBoard Live VPS to a dedicated server for better streaming performance. As such, the IP has changed, so I'm making this PR to get the OBL subdomain to point at the new address. This won't be a regular occurrence.
Thank you!

Updating live.onboard.hackclub.com

---

hackclub.com.yaml

For process of setting up new Sendy SES region with AWS.

[Adding] SES dkims - Fixing HCB Sendy SES

---

hackclub.com.yaml

Added the following to hackclub.com.yml in order to get hackpad.hackclub.com live
```
hackpad:
ttl: 600
type: CNAME
value: cname.vercel-dns.com.
```
It will be used for main page of hackpad, a macropad-based YSWS I'm currently running.

[Adding] `hackpad.hackclub.com`

---

hackclub.com.yaml

I added the `barracoders.hackclub.com` subdomain due to out school blocking `barracoders.com` and not blocking any `.hackclub.com` subdomain. This website will allow my club to access important information about clubs meets and upcoming events and a place to share thier creations.

Adding `barracoders.hackclub.com`

---

dino.icu.yaml

A QR code generator. You can make Hack Club themed QR codes and easily download them _without_ being registered to a mailing list!
Find a demo at [qr.felixgao.dev](https://qr.felixgao.dev)

Adding qr.dino.icu

---

hackclub.com.yaml

Legacy verification form that redirects to the airtable form

Adding legacy.verify.onboard.hackclub.com

---

hackclub.com.yaml

Adding the awest subdomain for the Arvada West High School hack club website. Link to site: https://awest-hackclub.vercel.app/

Adding `awest.hackclub.com`

---

hackclub.com.yaml

We are hoping to add our Hack Club's website as a subdomain. The site itself is hosted on the Nest server. This subdomain will be used in our college to advertise and provide information about our club and potentially announce upcoming events.

Add Runshaw Hack Club subdomain

---

hackclub.com.yaml

Hi again! Nest requires me to add a TXT record for domain verification before I can set up the reverse proxy to work correctly. Thank you!

Add domain verification for runshaw.ac.uk

---

hackclub.com.yaml

The subdomain **philippines.hackclub.com** will be used to a website dedicated for the latest hackathons and any hackclub-related events in the Philippines. With the use of the said website, it can spread information about hackclub and it can engage more high schoolers to organize their own hackathons and start their own club at their respective schools.

Adding philippines.hackclub.com

---

hackclub.com.yaml

Using Gmail's "Send mail as" with `<city>@counterspell.hackclub.com` results in sent emails being marked as spam due to failing DMARC.

Updating counterspell.hackclub.com

---

dino.icu.yaml

Adding leo.dino.icu / lkmw.dino.icu
DNS configuration updates:
* Added CNAME records for `leo` and `lkmw` subdomains, both pointing to `wilkin.xyz` with a TTL of 600. (`dino.icu.yaml`, dino.icu.yamlR246-R255)

Adding leo.dino.icu / lkmw.dino.icu

---

dino.icu.yaml

I am creating `runshaw.dino.icu` as an email forwarder for members of [Runshaw Hack Club](http://runshaw.hackclub.com/) so they can sign up for github. I'm using dino.icu because email is not permitted on hackclub.com subdomains

Create, add MX record for runshaw.dino.icu

---

hackclub.com.yaml

Adds a subdomain (southhighhack) for my school's Hack Club in the hackclub.com.yaml file. Also adds a TXT record because the website is hosted on Vercel.
This website will serve as a hub for our club's activities, resources, and announcements and as a platform to showcase group projects created by our club.

Adding southhighhack.hackclub.com

---

hack.club.yaml

This adds ahoy.hack.club as a short link for highseas.hackclub.com!

Add ahoy.hack.club

---

hackclub.com.yaml

This is for the #time-capsule (aka The Hack Box) and the domain will be used for a map of all hackathons the time capsule has been. Here is my demo [here](https://time-capsule-map.vercel.app/)

Adding capsule.hackclub.com

---

hackclub.com.yaml

Adds DNS for newly created club, Italia, based in sicily. Website is work in progress.
adds club subdomain (italia.hackclub.com) that points to 185.151.30.185 (ipv4)

Adding italia.hackclub.com

---

hackclub.com.yaml

Was getting ssl errors - seen that on other similar deployment, one should create a new domain w/in heroku and bind it like this.

Fix hackstone ssl issues

---

hackclub.com.yaml

Adding the Official Dessert YSWS landing page url here. This is for our official YSWS, were you ship an Android app, and get the $25 to buy your google play dev license. Right now it's on netlify, and we want to have it have a .hackclub.com url. Thanks!

Adding dessert.hackclub.com

---

hack.club.yaml
hackclub.com.yaml

I am adding glenny.hack.club which points to my Github Pages site currently at ghc.bobbedbob.io.
This is for Glenny Hack Club which is an official Hack Club that will run in 2025 at Glen Waverley Secondary College, Melboburne, Australia.

Adding glenny.hackclub.com

---

hackclub.com.yaml

Reverts hackclub/dns#1475
Now that https://github.com/hackclub/high-seas/pull/1057 is merged we're back up!

Revert "Switch to high seas maintenance page temporarily"

---

hackclub.com.yaml

Hackerspace is an after-school girls-in-tech club that's held at a local makerspace in New Delhi, India that caters towards middle-school / high-school-aged girls and nudges them in the direction of STEM/Tech and Coding. We host workshops at different skill levels, teach industry specific skills (like git), provide mentorship to beginners, hack on projects and build things with tools at hand.
We’re affiliated with Hack Club and host a lot of events focused around their programs (like high seas, boba drops, fraps etc.). We usually meet every other week on Saturday at [redacted] makerspace in South Delhi or online via Zoom. As the club leader, it's necessary to note my experience in India where women in technical classes is a rare sight, and so, I'm dedicated to the cause of making tech …

Adding 'hackerspacein.hackclub.com'

---

hackclub.com.yaml

Translation of the main website in Romanian with all links linking back to the main website's specific urls, so for example if u click clubs you'll be redirected to hackclub.com/clubs instead of ro.hackclub.com/clubs which doesn't exist.

Add ro.hackclub.com

---

hackclub.com.yaml

Minus Twelve is my new YSWS which will begin this week.\
the page was previously hosted at https://sporeball.dev/minus-twelve and i'd like it to graduate from https://hackclub.github.io/minus-twelve now that the repo has been transferred.

Adding minustwelve.hackclub.com

---

hackclub.com.yaml

Added subdomain to host a hackathon voting system for the events team. Also added Vercel verification record.
cc @devenjadhav

Adding podium.hackclub.com

---

hackclub.com.yaml

added new subdomain berman.hackclub.com to be used by the new berman hackclub. Currently the page redirects to the club google chat, but its already on cloudflare pages so it will be able to be easily switched to a website once we get that built.

Adding berman.hackclub.com

---

hack.af.yaml

The intention is to move hack.af (and only hack.af - not hack.club yet) requests to Coolify.

Redirect hack.af requests to coolify

---

dino.icu.yaml

This is a temporary change to handle a client that's accidentally generating a lot of requests to airtable during the end of high seas https://hackclub.slack.com/archives/C07PZMBUNDS/p1738476907877469

Remove skyfall.dino.icu high seas client

---

hackclub.com.yaml

DNS for hack club's print legion, a distributed printing network for YSWSes

[Adding] `printlegion.hackclub.com`

---

hackclub.com.yaml

This brings api2.hackclub.com & airbridge.hackclub.com to self-hosting!

Switch api2 to coolify

---

hackclub.com.yaml

Switching `hcb-test.hackclub.com` from Coolify to Heroku so that I can practice doing a switch from Heroku -> Coolify and monitor for potential downtime.

Switch `hcb-test.hackclub.com` to Heroku for practice migration

---

hackclub.com.yaml

I guess OctoDNS isn't happy with the alias??

Edit `hcb-test.hackclub.com` from ALIAS to CNAME

---

hackclub.com.yaml

not crazy short, but also not too long to sustain much downtime if we need to switch back.

Set HCB's ttl to 5 mins

---

hackclub.com.yaml

This reverts commit 4d7a363a2b603f9905020df271ab62cbfa50d18f.
Bringing HCB back to Heroku to allow us to deploy without downtime (Coolify doesn't support rolling deploys with our setup).
This is temporary as we find a long-term solution.

Revert "Switch `hcb.hackclub.com` to Coolify! (#1556)"

---

hackclub.com.yaml

Adding suceava.hackclub.com. Will be used for the club's website, where we present our club, present projects, make submission forms for registration, etc.

Adding suceava.hackclub.com

---

dino.icu.yaml
hackclub.com.yaml

Added a streaming/media service for Hackclub called HackTV
This is a media streaming website for hackclub, currently its using my nest server [conversafe.hackclub.app](conversafe.hackclub.app) , but would be great if we could get a better subdomain(Conversafe is an old project of mine) (Its a team project!). The website is open-source and a WIP, but available [here](https://github.com/TalenMud/HackTV) .  The idea is that hackclubbers would display their projects/ upload tutorials there, or if they want they can do live streams too(currently using WebRTC)
Thanks!

Added HackTV

---

dino.icu.yaml

Adding `baguette.dino.icu`

---

dino.icu.yaml

the you-ship-we-vote.dino.icu domain would be used to serve the main site, the backend.you-ship-we-vote.dino.icu would be used to serve the backend and db.you-ship-we-vote.dino.icu would be used to serve the supabase db.

Adding `you-ship-we-vote.dino.icu`, `backend.you-ship-we-vote.dino.icu`, `db.you-ship-we-vote.dino.icu`

---

README.md

Theres a bug with OctoDNS, where if you edit a file to remove a CNAME record and replace it with something else, it will fail to deploy.
To do it properly, you need to first make a PR that deletes all records, then make a second record which adds your records back another record in place of the CNAME. 
A lot of people were affected by this, so I edited the README to clarify a procedure on how to do this

Add more clear documentation about what to do when you're removing a CNAME and putting other records

---

hackclub.com.yaml

Changed NEST txt verification to club leader username because he had issues with Nest now it is working properly for him

[Updating] `scriptingnest.hackclub.com`

---

dino.icu.yaml

@recaptime-dev's [proxypartylab service](https://github.com/recaptime-dev/proxyparty-caddy) is down atm due to costs, so I have to hook up Deno Deploy with a bit of [Hono](https://hono.dev) for redirects, hence the additional `_acme-challenge` CNAME records.
Also in this merge request/patch is the inclusion of [my identity proof](https://keyoxide.org/aspe:keyoxide.org:DNHOHR4QWFIX5ZNPHAN4I2FWOI) for Keyoxide using [the modern Ariadne Signature Profiles spec](https://ariadne.id/related/ariadne-signature-profile-0/) instead of wrangling around OpenPGP pubkey annotations.

chore(dino.icu): update `[andreijiroh|ajhalili2006].dino.icu` to use Deno Deploy for redirects

---

dino.icu.yaml

Reverts hackclub/dns#1684
@ajhalili2006 I had to revert this since it broke the prod dns deployment workflow

Revert "chore(dino.icu): update `[andreijiroh|ajhalili2006].dino.icu` to use Deno Deploy for redirects"

---

hackclub.com.yaml

This subdomain will be used for the Hacklet YSWS project.

Adding hacklet.hackclub.com

---

hackclub.com.yaml

This adds a coolify-hosted status checker page for hackatime!

Add status endpoint for hackatime status checker

---

hackclub.com.yaml

Hackarest is a Hack Club organized in Bucharest. My co-organizer and I intend to use this subdomain as a 'placeholder' while we gather the money for a more permanent one.

Adding hackarest.hackclub.com

---

hackclub.com.yaml

Adding in the site for the [Fremont High School](https://fhs.fuhsd.org/) Hack Club 
This club hasn't existed for a while, removing it to reduce ambiguity (hasn't been active in a long time
Will be used for the FHS Hack Club

Remove fhsprogramming.hackclub.com, add fhs.hackclub.com

---

hackclub.com.yaml

Reverts hackclub/dns#1766
Once again, due to the CNAME bug

Revert "hc organizer"

---

hackclub.com.yaml

We decided to keep https://reactive.hackclub.dev

remove reactive

---

hackclub.com.yaml

[Add Google Site verification to DNS for Bank Android Developer acct.](https://github.com/hackclub/dns/commit/62882d0e5a71467202b3f3c3b6be5376a4a13f0b)

Add Google Site verification to DNS for Bank Android Developer acct.

---

dino.icu.yaml

Will reattempt to do https://github.com/hackclub/dns/pull/1684, possibly via Nest (fingers crossed) or other means. See https://github.com/hackclub/dns/pull/1686 for context and the original revert patch.

temporarily comment out ajhalili2006 and andreijiroh DNS records for dino.icu as workaround

---

hackclub.com.yaml

trying to add a google search console TXT record but apparently you can't combine TXT and CNAME :sob: (who built these standards weh)
[PART **1/2**] (merge this before part 2/2) - this PR removes news.hackclub.com as per the instructions on the readme

change news.hackclub.com to an alias and add a txt [1/2]

---

hackclub.com.yaml

The minecraft server is going back to the Contabo VPS.

Revert minecraft DNS to Contabo server

---

hackclub.com.yaml

`chronicle.hackclub.com` has an A record pointing to an IP that Hack Club no longer has control of. This was flagged as a subdomain takeover.

Remove Chronicle

---

hackclub.com.yaml

(currently hosted at reactive.hackclub.dev)
cc @JaredSene (hq sponsor)

Adding reactive.hackclub.com
